### ISSUE TITLE
2.a.2 Disaggregation not showing

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#103]
This indicator has 236 separate values and at the moment only 15 are visible (the 4 headline, and the headline by ODA type). The Aid Broad Category Description (DAC 5 Code) and Aid Description (CRS Code) aren't showing.

Could this be where with have a 2 tiers of disaggregation limit? The trouble is that if a value has a CRS Code it then has a broader DAC 5 Code, and then an ODA type. I might have a work around if this is the case. Or is it simply that there are too many different CRS codes (around 20)?

https://datasciencecampus.github.io/sdg-indicators/2-a-2/

**Comment by dougmet** [comment]
Hi Max, yes it looks like it's because of the high level of nesting. You'd need three boxes checked to see most of this data set (which we currently block). There's no formal limit of the number groups within a disaggregation.

Data of this form was not something we originally considered but it seems to be quite common so we may need to come up with a plan. Filters might fix it.

**Comment by MaxEngledew** [comment]
Yes, unfortunately at the very least all of the overseas development aid indicators (10-20) will likely be a similar format. Interested to see what this means going forward!

**Comment by dougmet** [comment]
Directly relates to #129

**Comment by nathaneastwood** [comment]
@MaxEngledew would you say that this is now solved as of b9f00f4? (i.e. the new filtering system)

**Comment by MaxEngledew** [comment]
Specifically, yes. We can now access all of the data through the filtering. 

However, accessing the 'deeper' data is not very accessible. Without our working knowledge of which disaggregation sit under which it can be quite confusing. I can try break this down into individual issues or would it be more helpful to start a thread on issues relating to the filtering update in general?

**Comment by nathaneastwood** [comment]
Could you initially provide an example of what you mean?

**Comment by MaxEngledew** [comment]
Sure. If you look at [5.2.1](https://datasciencecampus.github.io/sdg-indicators/5-2-1/) for example all the disagreggation appear selectable but if were to select "Age Group" variables you get no data appearing. From there, for most, its a guessing game of how to get that data to appear - only we know that all "Age Group" data sits under "Abuse Category: Non-sexual" . 

This same issue is applicable in many indicators and many cases. Essentially the hierarchical nature of many disaggregations still isn't clear.

**Comment by MaxEngledew** [comment]
The "grey out" enhancement you showed us doesn't seem to be working.

**Comment by nathaneastwood** [comment]
No that was a design decision. It doesn't actually make sense in some instances to do that, I will give an example at the next show and tell.

**Comment by AnnCorp** [comment]
Is this one that still needs looking at - for sprint 7?

**Comment by AnnCorp** [comment]
Closing this ticket and will have specific one with more detailed requirements agreed at SDGs meeting 5 Oct
