### ISSUE TITLE
Metadata not showing 

### ISSUE THREAD

**Issue by AlexLewis1** [datasciencecampus/sdg-indicators#106]
Doug has told me that I have been updating the metadata in the raw metadata section instead of the metadata fields. The indicators that I have done this for are 8.1.1, 8.2.1, 8.b.1 and 3.2.2. I'll move these around as soon as I can.

**Comment by nathaneastwood** [comment]
@AlexLewis1 have you managed to do this?

**Comment by nathaneastwood** [comment]
@AlexLewis1 and @MaxEngledew any updates on this?

**Comment by AlexLewis1** [comment]
The metadata is now showing as I was not updating the raw metadata initially so we can close this issue.
