### ISSUE TITLE
Medium Priority AA - Headings illogical

### ISSUE THREAD

**Issue by gingerbenw** [datasciencecampus/sdg-indicators#1063]
![screen shot 2017-11-02 at 10 34 59](https://user-images.githubusercontent.com/24570483/32321595-828ddd50-bfb9-11e7-81a6-5aec33939530.png)

The headings structure throughout the templates is illogical. Screen reader users rely on well-structured headings to determine the layout of the page and relationships between sections of content.  

**Solution:** Ensure headings are logically structured; the `<h1>` introducing the main content of the page and subheadings following in a logical order through `<h2>` to `<h6>`.

**Comment by dougmet** [comment]
Just needs the search page adding. The titles in results are `<h4>` but need to be `<h2>`

**Comment by gingerbenw** [comment]
Awaiting closure of #1167 to resolve

**Comment by gingerbenw** [comment]
#1472
