### ISSUE TITLE
FAQs - Medium Priority AA - Headings illogical

### ISSUE THREAD

**Issue by gingerbenw** [datasciencecampus/sdg-indicators#1064]
![screen shot 2017-11-02 at 10 36 35](https://user-images.githubusercontent.com/24570483/32321659-bada9b80-bfb9-11e7-8f85-2c513fdfda5d.png)

The headings structure throughout the templates is illogical. Screen reader users rely on well-structured headings to determine the layout of the page and relationships between sections of content.  

**Solution:** Ensure headings are logically structured; the `<h1>` introducing the main content of the page and subheadings following in a logical order through `<h2>` to `<h6>`.

**Comment by AnnCorp** [comment]
@gingerbenw is this one all finished so OK to close?

**Comment by gingerbenw** [comment]
Yes! this was completed along with #1063
