### ISSUE TITLE
No poverty 1.2.1 - High priority A - Content not understandable and predictable

### ISSUE THREAD

**Issue by gingerbenw** [datasciencecampus/sdg-indicators#1067]
![screen shot 2017-11-02 at 10 43 42](https://user-images.githubusercontent.com/24570483/32321947-b65bd4ba-bfba-11e7-92cb-1a6a7fac7011.png)

The ‘sub-categories’ section is not descriptive for screen reader users; the functionality or purpose of this area is not clear for users that rely on audio feedback.  When a selection has been made the graph updates, however this is not relayed to a screen reader user and not illustrated within the table alternative. The table does not reflect the male/female ratio, for example.  

**Code Ref(s):**    
```html
<div id="toolbar">         
  <h5>Sub-categories</h5>         
  <button id="clear" class="disabled">Clear selections <i class="fa fa-remove">  
```

**Solution:** Ensure that users are aware of the purpose of this area and how the page will be affected when a selection is made. An accessible alternative that displays all of the ratios is also required.

**Comment by dougmet** [comment]
I've moved the "An accessible alternative that displays all of the ratios is also required." part to #1150 so this ticket is about adding explanatory text into the side bar so that it's clear to screen reader users (and everyone I guess!) what you're supposed to do with it.
