### ISSUE TITLE
Disaggregation Interactions in the Plot

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#107]
The data model already has the interaction. See #68 . This is where, for example, we have data for say Sex and Region then we don't see the data rows where both are present.

Somehow we'd like to have the interaction data on the plot. This is potentially a **lot** of data for a plot. We may need some sort of filter applied first, or an option to toggle between separate breakdowns or interactions.

Either way we can discuss on this ticket and try some things out.

**Comment by nathaneastwood** [comment]
This is linked to #129

**Comment by nathaneastwood** [comment]
Closed via b9f00f4
