### ISSUE TITLE
No poverty 1.2.1 - Usability - Data tables

### ISSUE THREAD

**Issue by gingerbenw** [datasciencecampus/sdg-indicators#1070]
![screen shot 2017-11-02 at 10 49 47](https://user-images.githubusercontent.com/24570483/32322210-a540ae16-bfbb-11e7-9c78-8c5539d3d641.png)

It may not be clear to screen reader users what the table contains as there is no <caption> element to describe this.  

**Current code Ref(s):** `<table class="table-responsive table table-hover dataTable no-footer" id="indicatortable0" role="grid" style="width: 848px;"><thead>`

It is recommended that a <caption> is provided for the all tables on the website to enable screen reader users to quickly determine the purpose of the table and what it is displaying.

**Example:** `<table class="table-responsive table table-hover dataTable no-footer" id="indicatortable0" role="grid" style="width: 848px;"> <caption>Percentage of the population living in households at risk of poverty</caption> <thead>`

**Comment by dougmet** [comment]
@AnnCorp mentioned adding the standard footnote information (same as the chart) next to table as well. Either a footnote element or a caption. So we'll add units of measure, source, and geography.

**Comment by gingerbenw** [comment]
#1540
