### ISSUE TITLE
No poverty 1.2.1 - Usability - Accessible versions

### ISSUE THREAD

**Issue by gingerbenw** [datasciencecampus/sdg-indicators#1071]
![screen shot 2017-11-02 at 10 52 23](https://user-images.githubusercontent.com/24570483/32322293-ed1b05d8-bfbb-11e7-9cfb-48d93e62259d.png)

An accessible alternative has been provided for the graph features, however this may not be clear to all users as this appears below the fold; some may not see this and visually impaired users that rely on audio feedback would have to navigate through a lot of content before arriving at this.

**Solution:** It is highly recommended that a skip link to the accessible alternative be provided at the top of the graph feature for those that may require it. Suggested code: `<a href="#data" >Accessible graph alternative</a>`

**Comment by dougmet** [comment]
Put the button above the chart. If possible in a row above the sub categories. Must be clear that this is the link to the accessible alternative.

Need to make sure that it only displays when the chart displays.

**Comment by dougmet** [comment]
Can we also add a link to the source download?

**Comment by gingerbenw** [comment]
We could just add a link to the table anchor - this would mean clicking this button would simply take you straight to the table at the bottom of the page with the download for both the headline data and the source

![screen shot 2017-11-06 at 16 50 08](https://user-images.githubusercontent.com/24570483/32452842-9282c7b4-c312-11e7-98e3-b37c8ef59e92.png)

**Comment by gingerbenw** [comment]
After clicking button:

![screen shot 2017-11-06 at 16 51 49](https://user-images.githubusercontent.com/24570483/32452923-d152ca66-c312-11e7-926d-b92de87068fa.png)

**Comment by gingerbenw** [comment]
Please see commit #1454
