### ISSUE TITLE
Reporting status - Coming in Spring 2017

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#110]
Text needs updating. Maybe to Summer 2017?

**Comment by shaneporter** [comment]
Southern hemisphere or northern hemisphere? ;)

**Comment by nathaneastwood** [comment]
Closed as of 1ee8d24981957969d335d75f195fa2bcbc50ea5c

**Comment by shaneporter** [comment]
Is it closed because that page now shows the 'This is a development website for collecting and disseminating UK data for the Sustainable Development Goal global indicators. Currently data on the site may be test data. Please send any feedback to sustainabledevelopment@ons.gov.uk' disclaimer?

**Comment by nathaneastwood** [comment]
Well we now have a reporting status page :D and it doesn't have the text there anymore 👍
