### ISSUE TITLE
Data source should be included with the chart

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#112]
This is so that people don't have to go looking for the source in another part of the page.

Other metadata may need to be added too (see user story on Trello). For example, we should be able to pick out key information for things such as axis labels and unit of measurement.

**Comment by nathaneastwood** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User story: chart standards](https://trello.com/c/CgeEcfVR/60-user-story-chart-standards)

**Comment by nathaneastwood** [comment]
Other metadata may need to be added too (see user story on Trello)

**Comment by nathaneastwood** [comment]
We should be able to pick out key information for things such as axis labels and unit of measurement.

**Comment by shaneporter** [comment]
So the key points from ![](https://github.trello.services/images/mini-trello-icon.png) [User story: chart standards](https://trello.com/c/CgeEcfVR/60-user-story-chart-standards) are:

1. Have a title describing the chart
2. Clearly show the period(s) the data covers
3. Show the geographical coverage
4. Show the unit of measurement
5. Show the data source(s)

@dougmet:
numbers 3 and 5 - are they in the metadata? Can you point me in the right direction? Thanks.

**Comment by dougmet** [comment]
3. This is in the source metadata: source_geographical_coverage_1 but is often a long string

5. I think data source will be the source organisation. Use `source_organisation_1` from the metadata.

**Comment by dougmet** [comment]
Hi @AnnCorp is this a good example for us to use as a guide? https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/lf24/lms

**Comment by dougmet** [comment]
I also see that geographical coverage is in the main metadata: `national_geographical_coverage` which may be the better choice.

**Comment by nathaneastwood** [comment]
Can we close this issue now @shaneporter?
