### ISSUE TITLE
Add alpha logo

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#114]
The GDS are currently using an alpha logo on one of their websites and we should be using something similar. This would replace (or compliment?) the message displayed in the red box.

@AnnCorp do you have a link?

**Comment by nathaneastwood** [comment]
[This link](https://www.gov.uk/service-manual/design/alpha-and-beta-phase-banners) is an example of what we need to us.

**Comment by shaneporter** [comment]
It's my understanding that the 'alpha' software development phase relates to the feature set of the software, and that the software may be buggy as hell. It does not relate to the data.

Therefore, it makes sense to have both, no?

**Comment by nathaneastwood** [comment]
@dougmet any thoughts on this? I think we are going for both?

**Comment by AnnCorp** [comment]
Yes, we are doing both. Think this one isa dupe ticket for the one Doug set up which has the text re test data too.

**Comment by shaneporter** [comment]
Both are implemented in PR #120.
