### ISSUE TITLE
Usability - Consider making the page titles short and concise

### ISSUE THREAD

**Issue by gingerbenw** [datasciencecampus/sdg-indicators#1142]

**Comment by dougmet** [comment]
To be clear this is the title as in the `<title>` tag, not the `<h1>` content.

**Comment by AnnCorp** [comment]
Assume this applies to the goals pages and indicator pages?
There is no shortened version of text for the indicator descriptions but as the purpose of this field for screen reader users is to determine the content of the page content, work it work if we just have something like  'Information for indicator x.x.x'?
For goals, we could use the shortened text version that's in the goal icons, or should we add something like 'Indicators within Goal x [goal short description]'

**Comment by gingerbenw** [comment]
That’s a good point - if ‘indicator x.x.x - [goal short]’ is doable, I think that would be perfect

**Comment by dougmet** [comment]
`indicator x.x.x - Goal [goal] [goal short]`

**Comment by dougmet** [comment]
see commit. Assigning to @gingerbenw

**Comment by gingerbenw** [comment]
Added another dash:

`indicator x.x.x - Goal [goal] - [goal short]`

Happy!
