### ISSUE TITLE
Style the sub-categories label a bit smaller

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1167]
`#toolbar h3`

**Comment by AnnCorp** [comment]
Widened this to cover the indicator page, not just the sub-categories bit.
Need to review and tweak the headings/styles used so accurately reflects hierarchy of things on page and have consistency (while adhering to the accessibility need for logical use of heading styles). [As non-techy not sure how the chart elements are controlled.]

Some things have noticed:
1. The sub-categories heading is bigger than the chart heading but it should be smaller
2. The heading for chart and the heading for table in Data tab are very different but are equivalent in hierarchy - chart heading to match table heading? Chart heading should also left align like other headings.
3. Within Data tab, the 'Headline data' title is the same size as table heading but should be smaller.

**Comment by gingerbenw** [comment]
Is this the heading that needs to be left aligned? I don't believe this is currently a heading, it's simply a caption on the chart - the heading is currently included lower on the page above the table.

![screen shot 2017-11-06 at 15 25 27](https://user-images.githubusercontent.com/24570483/32448451-cfef4796-c306-11e7-951f-20de0abca2cb.png)

**Comment by gingerbenw** [comment]
![screen shot 2017-11-07 at 09 34 31](https://user-images.githubusercontent.com/24570483/32486568-eb45467e-c39e-11e7-843a-0b582d42318f.png)

**Comment by gingerbenw** [comment]
![screen shot 2017-11-07 at 09 36 45](https://user-images.githubusercontent.com/24570483/32486671-32cee57c-c39f-11e7-94ad-34197fd3248c.png)

**Comment by gingerbenw** [comment]
headline data tag smaller

**Comment by gingerbenw** [comment]
Please see #1472
