### ISSUE TITLE
Wrong units in selection : Forests 15-2-1

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1184]
Steps to reproduce:

Load [15-2-1](https://datasciencecampus.github.io/sdg-indicators/15-2-1/)

Click geographies. Select all.

Disaggregation data shown on chart does not correspond to `Annual certified woodland area growth rate (%)`

![image](https://user-images.githubusercontent.com/5878305/32370829-581745fc-c086-11e7-9ba8-da6b1305b79a.png)

**Comment by AnnCorp** [comment]
@ dougmet @shaneporter I think this sounds the same as a bug Max just mentioned to me.
When you select a different unit, the data for that unit isn't reflected in the chart - it displays the data for the previously selected unit but showing it on the scale for the newly selected unit. Examples from Max:
8.4.1 Select tonnes per capita. Select biomass (value 3.2 in 2000). Switch to tonnes per GDP and value is still 3.2 (should be 132.7)
Ditto 9.2.1 looking at 2000 values percentage 1.75, per capita should be 421

**Comment by AnnCorp** [comment]
@sporter do you think this is the same issues as #688 or something different (am trawling through the bug tickets before adding new ones max raises...)

**Comment by shaneporter** [comment]
I _think_ that #688 is fixed too as a result of this change.
