### ISSUE TITLE
Chart headline legend to reflect geographical area

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1194]
The headline legend description on the charts says UK but not all indicators are UK eg
https://datasciencecampus.github.io/sdg-indicators/8-8-1/ is Great Britain
https://sustainabledevelopment-uk.github.io/16-1-1/ is England and Wales
So we need some way for the headline legend to accurately reflect the Geographical Area.

**Comment by dougmet** [comment]
Use the `page.geographic_area` instead of `site.country_name`
