### ISSUE TITLE
Add Source and Geographical area below Data table

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1199]
Under chart we have Source, Geographical area and Units. Need to replicate this under the data table on Data tab.
So need to move Units info and add in Source and Geographical area.

**Comment by dougmet** [comment]
I'm thinking of using a `<tfoot>` element for this, unless there's a big accessibility reason not to. I can't see anything to say it's bad (nor especially good). Other option is to put it all in the caption but that might overload it and would put it all at the top.

**Comment by dougmet** [comment]
Looks like `tfoot` is more for column totals, that sort of thing. I'm going to put this is a div.
