### ISSUE TITLE
Full time series not displaying unless deselect UK

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1202]
Eg 4.1.1 
Select a subject eg English and select Key stage 1 disagg. You'll only see data point for one time period even though there are multiple time periods. If you deselect UK, then all the time periods display - it seems to somehow be picking up the time series duration from the headline figure not the disaggregation?
There is one UK data point for Key stage 4 so behaves differently for that and displays all time periods.
Feasible that have differences in time periods between units and between diaggregations and headline

**Comment by dougmet** [comment]
I think this is a duplicate of #516

**Comment by AnnCorp** [comment]
fixed
