### ISSUE TITLE
Filtering should reflect data hierachy

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1204]
Within the hierarchical filtering, users can select subcategories when no data exists for that combination, but ideally they shouldn't be able to.
Examples:
https://datasciencecampus.github.io/sdg-indicators/3-1-2/ can select Wales as a country and then select any/all of the options in 'Region' but those regions don't exist for Wales data, only for England. Similarly if select England can then select any/all of the health boards but they only exist for Wales, not England
https://datasciencecampus.github.io/sdg-indicators/2-a-2/ the Rural Development subcategory within 'Aid descriptions' is only valid where 'Aid broad category' is 'Other multisector' and all the other aid descriptions are only valid when aid broad category is Agriculture.
Team suggest shouldn't be able to select something if no data exists for it and so will not be displayed.

**Comment by AnnCorp** [comment]
@shaneporter @dougmet have no idea of the complexity or time involved in providing a solution to this - doesn't seem like a simple thing. 
Be good if you could discuss and come up with some suggested options, if poss please, so can gauge how big a job it would be to fix.
In our team there's various views on if shouldn't see the subcategory at all if can't select it or if things should all be visible but not selectable if no data for it (I can see value in seeing stuff or user wouldn't know what exists without clicking through everything)

**Comment by AnnCorp** [comment]
Just moved this out of 'Done' as think was put there by mistake!

**Comment by gingerbenw** [comment]
Hi Ann, sorry I closed the Pull Request but left the ticket open and only moved it - I believe Brock has solved this so we can close it!
