### ISSUE TITLE
Supported browsers

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#123]
I'm taking a look at a couple of things, and being mindful of the browsers that the website is intended to support. I have found the 'Browsers to test in' section on the Government Digital Service's '[Designing for different browsers and devices](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices)' page.

Is this what we're aiming for?

Estimate: 1 hour

**Comment by nathaneastwood** [comment]
@AnnCorp can you comment on this?

**Comment by nathaneastwood** [comment]
Anything considered in the GDS should be supported.

**Comment by AnnCorp** [comment]
Closing as covered by issue 307
