### ISSUE TITLE
Support generic filtering

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#129]
Estimate: TBC

This ticket is for the first pass at supporting generalised filtering. Right now we can select up to two columns (groupings) and this applies a filter that these columns must be _not missing_. However, we need to support deeper levels of drilling down. So filtering to a single region, or .

We also need to support hierarchical data, such as that in 2-a-2 or now in 14-1-1 #124 where parent and child relationships have been defined #128 . This is done via a string in the metadata, `data_edge_list` and the format is comma separated pairs of `Parent:Child` directed edges. So for example in 14-1-1 `Planet` is a parent of `Continent`. The data looks like:

| Year|Grade |Planet |Continent |Fruit | Value|
|----:|:-----|:------|:---------|:-----|-----:|
| 2010| |Earth  |Africa    | | 5.807|
| 2010|     |Earth  |America   | | 5.268|
| 2010|    |Earth  |Asia      | | 5.557|
| 2010|    |Mars   |Dawes     |     | 8.026|

where the is **always** a value of Planet if Continent has been specified. The edge list is specified as

```yaml
data_edge_list: "2:3"
```
because column 2 (indexed from 0), which is Planet, is the parent of column 3, which is Continent.

This will require a fairly big change to the UI and the data model.

**Comment by dougmet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Story: Support Hierachical Data](https://trello.com/c/MepQAuDo/65-user-story-support-hierachical-data)

**Comment by nathaneastwood** [comment]
This should be detailed in the Wiki

**Comment by dougmet** [comment]
I'll try to put a draft in place before this sprint end.

**Comment by nathaneastwood** [comment]
I believe this is solved by b9f00f4?

**Comment by AnnCorp** [comment]
Closing this general ticket - will replace with specific ones.
