### ISSUE TITLE
Prose metadata fields 

### ISSUE THREAD

**Issue by AlexLewis1** [datasciencecampus/sdg-indicators#134]
Just a couple things I've noticed in the metadata section that could use a bit of tweaking; 'Other information' needs to be changed to source metadata, we need a definitions section in method of computation and the release date of the data source needs to be able to hold values like February to March 2018.

**Comment by dougmet** [comment]
Sounds OK. The date fields are currently just free text so you should be able to put in things like February to March 2018 as it stands (I didn't get around to putting in a hard check against that yet)

- [ ] Move `Other Information` to `source` scope
- [ ] Add definitions section to `computation` scope

**Comment by AlexLewis1** [comment]
Ah okay, I thought prose would throw that back at me, that'll be fine.
