### ISSUE TITLE
Add footnotes [1.5 hours]

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#136]
Some data is based on financial year, so runs April Year1 - March Year2. The `Year` column in our csvs needs to be numeric right now. We have a few of options:

- Add a footnote field to appear by the plot and the tables
- Add a simple "Financial Years" check box so that we can style it appropriately
- Support ordered non-numeric keys

Estimate: 1.5 hours

**Comment by nathaneastwood** [comment]
This is not just for financial years. We just need a "footnote" field that can include any kind of text. There can be more than one footnote - this should be a fillable box in Prose.

**Comment by dougmet** [comment]
What do we think. Is this a `computation` option? I'll start with that but if people want to move it to the chart options then we can do that too

**Comment by dougmet** [comment]
We're going with a footnote

**Comment by AnnCorp** [comment]
#177 may cover off this issue #136.

**Comment by AnnCorp** [comment]
for Sprint 6

**Comment by AnnCorp** [comment]
Confirmed Sprint 8

**Comment by dougmet** [comment]
I initially added this to the right hand side but it needs to move back to left hand side.

**Comment by dougmet** [comment]
Where has this gone?

**Comment by dougmet** [comment]
Looks like a merge in the indicator layout removed this. Now restored. @MaxEngledewAdmin could you take a look at https://datasciencecampus.github.io/sdg-indicators/14-1-1/ and let me know if this is what you're after?

**Comment by MaxEngledewAdmin** [comment]
This looks good to me - thanks Doug
