### ISSUE TITLE
Outdated Indicators

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#143]
Attached is an xls with the additional, revised, and removed indicators which need updating on the tool. 

[Indicator Updates (22.03.17).xlsx](https://github.com/datasciencecampus/sdg-indicators/files/1010752/Indicator.Updates.22.03.17.xlsx)

Estimate: 2 hours

**Comment by dougmet** [comment]
So 2.b.1 needs completely removing and the rest just need updating. Sound right?

**Comment by dougmet** [comment]
Oh, and add some new ones. `1.5.4` , `1.a.3`, `3.b.3`, and  `13.1.3`

**Comment by MaxEngledew** [comment]
That is correct, and the current 2.b.2 will become 2.b.1.

**Comment by dougmet** [comment]
I'm working through these but started to worry when I hit 3.8.2. The indicator looks very different but I can't find any other related metadata online. Has it really been updated or should we hold off?

**Comment by dougmet** [comment]
I'm working on branch ` e/outdated-indicators-143`

**Comment by dougmet** [comment]
https://sustainabledevelopment.un.org/sdg3

**Comment by AlexLewis1** [comment]
Hi Doug, no need to worry you can find the latest list through the following link: https://unstats.un.org/sdgs/indicators/indicators-list/

**Comment by nathaneastwood** [comment]
Could someone please provide an update on this?

**Comment by MaxEngledew** [comment]
It seems as though, although @dougmet started doing this, none of the indicators have been updated as the site stands. Just to confirm, the excel file at the top is a correct summary of the updates and the post 22/03/17 list needs to be implemented. The full updated list of SDG indicators can be found [here](https://unstats.un.org/sdgs/indicators/indicators-list/).

**Comment by nathaneastwood** [comment]
Thanks @MaxEngledew, I will catch up with @dougmet when he is back about this.

**Comment by MaxEngledew** [comment]
@dougmet This has still not been resolved the latest list of UN indicators and revisions can be found [here](https://unstats.un.org/sdgs/indicators/indicators-list/). This affects a lot of indicators as there has been additions, removals, and revisions. The tool needs to align with the UN list.

**Comment by AnnCorp** [comment]
@dougmet Pls could you make this your top priority job -  we need to get the indicators matching the UN versions asap. We can discuss if anything needs to slip down the list to accommodate this. 
Please could you liaise with @MaxEngledew if theres any work you need his team to do to get the list from UN into a better format for you to load.

**Comment by dougmet** [comment]
Hi @AnnCorp, I'm starting to pick this up now. It's a pretty big data merge and I'm building some tools to help me.

**Comment by AnnCorp** [comment]
Great - thanks. More of your useful tools to keep for reuse then…

**Comment by dougmet** [comment]
Killing the original branch for this and starting again on `b/143`

**Comment by dougmet** [comment]
Wow, this turned out to be complicated! Lots of files needed updating. I've now got it all scripted.

FYI @AnnCorp and @MaxEngledew it's a bulk metadata update and this will cause issues for inbound PRs. Sorry about this, I had to squeeze it in before the gh-pages branch updated again (which makes me have to start again).

You can either manually fix the conflicts in GitHub or you can resubmit those PRs

**Comment by dougmet** [comment]
Up to 244 now though :-)

![image](https://user-images.githubusercontent.com/5878305/31549410-01f4019e-b026-11e7-999f-001d29f8e3fa.png)

**Comment by MaxEngledewAdmin** [comment]
@dougmet New pull requests still say they are out of date with the base branch - what should we be doing. Hitting update?
