### ISSUE TITLE
Further chart improvements

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#152]
From the user testing, further improvements were identified to make the charts better.

Must:
- [ ] It is difficult to distinguish between the colours on the chart. One suggestion is to increase the contrast between the lines, another is to make the colours blue and grey with the "All" line in red
- [ ] Legends should be filled rather than hollow
- [ ] The title, source and geographical area should be left aligned to the chart
- [ ] The height of the chart needs to be increased. Currently it looks squished and makes it difficult to distinguish between different lines.
- [ ] Add the unit of measurement as a subtitle
- [ ] On the tooltip, we should have (as an example) "Northern Ireland" as opposed to "Geographical Coverage Northern Ireland"

Could:
- [ ] Is it possible to have zoom functionality on the chart to more easily identify individual points? (Depends on how much increasing the chart height helps to visualise individual points that are overlaid)

**Comment by shaneporter** [comment]
Can we separate this list into separate issues? There's quite a lot going on. In particular, the last issue is a lot more work and its continued discussion/implementation would cloud the status of the other issues somewhat.

**Comment by nathaneastwood** [comment]
Re: increasing the height of the graphic:
One suggestion is to make the logo smaller permanently instead of when the user scrolls down. This will give us more vertical space to work with.

**Comment by shaneporter** [comment]
I've split this issue into several new ones: #181, #182, #183, #183, #184, #185, #186, #187
Closing this one.
