### ISSUE TITLE
Update the LICENSE file

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#160]
We should be using the Open Government License v3

**Comment by dougmet** [comment]
Just to check. Does this sit OK with the CC0 license that the US have? I think we can do that but I'm just checking seeing as we've built on their work.

**Comment by nathaneastwood** [comment]
Well whilst I agree we need to check, I would argue the work has diverged enough?

**Comment by dougmet** [comment]
Probably, yes. We could have a custom license which acknowledges we forked from the US version and print their license and link to their development page.

(btw there's a parallel discussion on the PR)

**Comment by dougmet** [comment]
My main concern is violating CC0 so we should check it. It's possibly the most permissive license going so we're probably OK

**Comment by nathaneastwood** [comment]
> Is there any precedent for licensing the data on OGL and the site on CC0? Or somehow blending the license from the US version and our version. Just want to make sure we've done right by all parties.

With regards to this question, when it comes to ONS "stuff", we must use OGL-3 unless it is simply code in which case we are allowed to use MIT.
