### ISSUE TITLE
Tweak text in 'i' info box

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1620]
Currently all indicator pages  have an 'i' info box that says 'See metadata tab for sources, definitions, and methodology information'
As the Sources are in a separate tab, please change the text to say 'See Metadata tab for definitions and methodology information'

**Comment by AnnCorp** [comment]
@gingerbenw pls could this one be next after looking at zeroes bug.

**Comment by gingerbenw** [comment]
Fixed - #1713
