### ISSUE TITLE
Graph title is not changing with prose

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#165]
![capture](https://user-images.githubusercontent.com/24583650/26916285-a8ed67f6-4c21-11e7-9182-384e9f701567.PNG)

We seem to still have a U.S. graph title despite changing the field to "Mortality rate for infants and children younger than 5 years old per 1,000 live births" in prose. This only seems to have changed the table title (example: https://datasciencecampus.github.io/sdg-indicators/3-2-1/).

**Comment by nathaneastwood** [comment]
Hi @MaxEngledew this seems to do with the metadata. For this particular indicator, the metadata states:

```
actual_indicator_available: >-
  Mortality rate for infants and children younger than 5 years old in the United
  States
```

**Comment by nathaneastwood** [comment]
I have resolved this myself

**Comment by dougmet** [comment]
I think we need to start making it clear which bits of metadata will change what. We can rename and add new ones if necessary.

**Comment by nathaneastwood** [comment]
@dougmet this stuff needs to go in a Wiki. I will be in the office next Friday and we can discuss/document it then maybe?

**Comment by MaxEngledew** [comment]
That would be really helpful. From what I can tell:

"Graph Title", which is hidden all the way down under source 3, changes the table title but not the graph. Surely these should both be fed in from the same field? 

"Actual Indicator Available" prose field doesn't seem to feed into the raw metadata "actual_indicator_available: >-" which, in turn, changes the graph title.
