### ISSUE TITLE
Prose Error

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#166]
Trying to update metadata and getting this error on attempts to commit:

> Could not update file: Required Status Check "continuous-integration/ travis-ci" is expected. At least one approved review is required by reviewers with write access.  

We can't make sense of this!

**Comment by dougmet** [comment]
I think this may be to do with your new write permissions. Am discussing with @nathaneastwood

**Comment by nathaneastwood** [comment]
This was indeed to do with the permissions. Closing
