### ISSUE TITLE
Footnotes on charts should wrap long text

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1748]
Where there is long footnote text, it isn't all displaying - need it to wrap please (wraps fine where occurs under data table)
Example: https://datasciencecampus.github.io/sdg-indicators/3-a-1/

**Comment by AnnCorp** [comment]
@gingerbenw is this one you could look at please?

**Comment by gingerbenw** [comment]
I have got the text to wrap correctly at the nearest space around 128 characters, the issue at the moment is dynamically setting the padding for the height of the text.

**Comment by gingerbenw** [comment]
complete! thanks Shane for the text wrapping :)
