### ISSUE TITLE
Area for non-standard information [estimate 1hrs]

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#177]
We need somewhere where we can include information on, for example:

  1. Non-statistical indicators
  2. UN data as a proxy

This needs to take precedence at the top of an indicator's page as the data cannot be hidden away in the metadata.

Tasks remaining:

- [x] Style the table (add padding)
- [x] Add section separator (or padding)
- [x] Add a wiki entry for how to use this

Estimate: 1 hours

**Comment by nathaneastwood** [comment]
This also needs to include the option of whether or not a graph should be displayed.

The area should be a free text area in Prose.

**Comment by dougmet** [comment]
This could be either a free text box in the metadata (possibly the best) or we could use the markdown body for this, e.g.

```
---
# metadata
item1: value1
item2: value2
---

## A heading

Some markdown text with [hyperlinks](http://example.com) and all sorts of things

```

**Comment by nathaneastwood** [comment]
Is there a risk there that non-technical people would need to then "learn" markdown? I know there is a WYSIWYG helper, but people still need to know how they work.

**Comment by dougmet** [comment]
It turns out the page content already goes in. I've added a demo of this to indicator 14-1-1 in PR #276. Anything you write below the yaml header in the md (or simply in the content section in Prose) will appear above the chart.

**Comment by AnnCorp** [comment]
Discussed with SDG team 13/09/17. Requirements for this:
- free text field (query: if don't have character limit, how handle display of long entries of just let box take as much apace as needed?)
- want ability to format text eg add bold etc
- want to be able to add hyperlinks on text so don't have to include full URL text

**Comment by dougmet** [comment]
Hi, I've implemented a test, see https://datasciencecampus.github.io/sdg-indicators/14-1-1/ where there is now some free text at the beginning.

The text is entered outside of the metadata as Markdown (see the raw file [here](https://raw.githubusercontent.com/datasciencecampus/sdg-indicators/gh-pages/_indicators/14-1-1.md)) and is more like a document than data.

**Comment by AnnCorp** [comment]
@dougmet have asked the team to test setting one up based on your example.

**Comment by dougmet** [comment]
The only thing that doesn't look good out of the box is the table style. This is a super easy change, and I'll make a new ticket for it.

**Comment by dougmet** [comment]
Indicator 14-1-1 has one of these. Also the wiki is updated [here](https://github.com/datasciencecampus/sdg-indicators/wiki/Metadata-format)

**Comment by AnnCorp** [comment]
OK to close. New data inputters will trial as they add more data.
