### ISSUE TITLE
Additional Global metadata fields

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#18]
@nathaneastwood @shaneporter  Revising this issue/requirement to cover wider than global metadata. Specifying changes to global metadata and uk metadata - indicator specific and source specific. Document listing requirements is with Jen Thomas for review and amending - will pass on once Jen has completed her comments.
Key change: needed to have source-specific metadata within an indicator where there can be one or many sources so there won't be a fixed number per indicator.

**Comment by dougmet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SDG team to specify detailed requirements for metadata and data collection](https://trello.com/c/skpfdUyf/43-sdg-team-to-specify-detailed-requirements-for-metadata-and-data-collection)

**Comment by dougmet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User story: add fields for metadata](https://trello.com/c/Zadn1MyB/51-user-story-add-fields-for-metadata)

**Comment by dougmet** [comment]
Variable data sources is entirely possible in the yaml (raw data format we're using) but possibly challenging in prose.io. Have added #35 to this sprint to investigate

**Comment by dougmet** [comment]
It's not simple to have variable data sources without creating our own prose fork. I've looked into that and it's not too bad. prose is a fairly simple node app and I've already tried setting up a gateway on heroku and it works. See #38

**Comment by nathaneastwood** [comment]
This is done.
