### ISSUE TITLE
Add statement re privacy and cookies

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1865]
Raised by Shane 'Does the site currently have a cookies explanation, because it uses them for Google Analytics?'
ONS website has a Pivacy and cookies' statement  here https://www.ons.gov.uk/help/cookiesandprivacy
Another example from Shane from The Guardian https://www.theguardian.com/info/cookies

**Comment by AnnCorp** [comment]
Take the ONS text to start with

**Comment by AnnCorp** [comment]
@gingerbenw  looks good thanks. Know this is a  straight lift from ONS text, but does the cookies list in the text accurately reflect what we would be using on the SDGs site too - I have no knowledge on this kind of thing.

**Comment by gingerbenw** [comment]
I think a large portion of this can be cut out - we don't use most of those cookies, in fact the only one I have active on my session is the contrast cookie. I shall have a filter through it now and update

**Comment by AnnCorp** [comment]
Have seen updated Cookies page text from Ben so assume all ok to close this now.
