### ISSUE TITLE
Data tables do not indicate sort column and sort direction

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#1869]

**Comment by AnnCorp** [comment]
People seem to find the table sort feature quite handy when they know aobut it but don't realise its there. Adding something like this could make it more overt. 
@shaneporter @dougmet what options do we have re this please and how long do you think it would take?

**Comment by shaneporter** [comment]
We already have the necessary html, it's just a case of adding some background images. 

Effort required: < 1hr.

**Comment by norric1** [comment]
Checked - working as expected.
