### ISSUE TITLE
All but the first column in tables should be aligned right.

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#1873]
Currently the numbers are aligned left, but they should be aligned right, as described here:
https://style.ons.gov.uk/data-visualisation/tables/number-alignment/

**Comment by shaneporter** [comment]
In fact, this applies to the 'value' column only, since on the ONS website, years are left aligned.

**Comment by shaneporter** [comment]
All columns other than the first should be right aligned.

**Comment by AnnCorp** [comment]
@shaneporter is this one for @dougmet to review then push the change through (rather than for Max and I yet)?

**Comment by shaneporter** [comment]
Yes, I assigned @dougmet to review, and he raised an issue with my change.

**Comment by shaneporter** [comment]
Opening a *new* issue for the units - #1929.
