### ISSUE TITLE
Add code for Loop 11 user testing

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1879]
We plan to remotely do some usability testing by using Loop11. Our web team have used it and advised we need to add code to our site to make it work with Loop11. 
The code will be the same as on this site https://discovery.onsdigital.co.uk/datadiscovery/ ie
<script type="text/javascript">
  window.loop11_key = "0104054b3b56d396b42e668dfe096cee161454a8";
</script>
<script src="//cdn.loop11.com/my/loop11.js" type="text/javascript" async="async"></script>
@gingerbenw @shaneporter what (if any) further info would you need to get this up and running please?

**Comment by gingerbenw** [comment]
It actually looks as though that's everything we need. I will add this to the page and we can then see if they can test it. will this be going on the master page, or the development?

**Comment by dougmet** [comment]
I think I just asked he same question on the PR. If it is just for staging (develop) then there is a `site.environment` variable you can use to distinguish

**Comment by AnnCorp** [comment]
@gingerbenw  In first instance its master to test the stuff already live. 
I can see circumstances where in future may wish to test on master or develop - bulk public testing from master once have pushed something live but poss smaller scale testing of new features on develop when dabbling with something new.

**Comment by AnnCorp** [comment]
@gingerbenw forgot to ask...do you have time to get this in place in next day or two if poss please so our user research lead can get some test links set up. Thank you!

**Comment by gingerbenw** [comment]
Please see #1880 

This has been added - just trying to figure out where to pull the changes to! it might need to skip the develop branch and go straight to production?

**Comment by gingerbenw** [comment]
Merged into development branch

**Comment by AnnCorp** [comment]
@nirenbasu is going to test he can pick up from the staging site and if all works ok we can push to master branch

**Comment by AnnCorp** [comment]
From Niren
"Can you confirm that the JavaScript has been added to all of the webpages. It appears to work on the homepage but doesn’t seem to be appearing for the others."

**Comment by AnnCorp** [comment]
I tested a version pointing at develop branch ans seem to be working ok (except hung on search - may raise a separate ticket if persistent problem).
