### ISSUE TITLE
Move data tab to table tab

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1883]
Now that we have our great `table` option next to the chart, the `data` tab seems redundant. The main use for the data tab is progressive enhancement (no JS or IE8)

Can we combine the data tab with the table tab, is it difficult? I think the main issue is how it works without JS. Things to consider:

* Must initially have the headline data table, and download button
* Chart tab shouldn't be there unless JS is
* Tab (key) movement through the page must still flow well
* Move the download source data button here

What I also like about this is that the metadata will be visible as soon as the page loads. Always felt a bit hidden.

Estimate: 3 hours (Doug)

**Comment by dougmet** [comment]
I can take I think, or @shaneporter if you prefer

**Comment by shaneporter** [comment]
If you want to take it, be my guest @dougmet.
