### ISSUE TITLE
Data hierachy should reflect unit selection

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1884]
The available selections can depend on the unit type but the available options don't update.

**Comment by dougmet** [comment]
Hi @MaxEngledewAdmin , could you quickly note down some steps to reproduce this?

**Comment by MaxEngledewAdmin** [comment]
@dougmet no problem! [2.3.1](https://datasciencecampus.github.io/sdg-indicators/2-3-1/)

Crop category and crop are only applicable to unit type: Land use (000s hectares)
Livestock is only applicable to unit type: Livestock (000s)
Geography, Timber category, and Ownership are only applicable to unite type: Timber (000s green tonnes)

So, for example, right now you can still select Geography if you have Land use unit type selected. I'll let you know if I come across another indicator example!

**Comment by dougmet** [comment]
Thanks. @shaneporter will take a look in the next sprint.

**Comment by AnnCorp** [comment]
@MaxEngledewAdmin  pls could you retest this one now fixed. and close with a commentif all ok.

**Comment by MaxEngledewAdmin** [comment]
Fixed!
