### ISSUE TITLE
Add link to search in front page text

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1885]
Change to:

> Click on each goal, or search, for UK statistics for Sustainable Development Goal global indicators.

where "or search" is an anchor that changes the focus to the search box.

**Comment by shaneporter** [comment]
Reminder to me, if I do it, or somebody else:

the search part is added if JavaScript is enabled, so the same should apply to the 'or search' part too.

**Comment by dougmet** [comment]
Good point

**Comment by dougmet** [comment]
Could have `display: none;` and js could switch it?
