### ISSUE TITLE
Max number of lines on graphs should be 13

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1887]
It looks like 15 lines are showing, whereas we were limiting to 12. There are grey lines appearing.

@shaneporter I'm not sure what I really mean here!

**Comment by shaneporter** [comment]
My thinking with an odd number of lines was headline + (2 x number of other colours, separated by line style).

**Comment by AnnCorp** [comment]
I'll contact DAC re some advice on colour options to use - that may impact what we go for.

**Comment by shaneporter** [comment]
I'll wait for a response on this one before I tackle it.

However, please also let me know if the limit should be an odd number. (Headline + (2 * colour, one for each line style)).

**Comment by dougmet** [comment]
For me it's really when do we run out of colours. So I don't mind 12 vs 13. What you say makes sense so happy to say 13.

**Comment by AnnCorp** [comment]
I've asked DAC for guidance re line chart colours/styles and example. - will share waht get back...

**Comment by shaneporter** [comment]
OK about the difference between the foreground/background, but there also has to be a clear difference between the different colours too. Could DAC specify the 6 different colours? Or shall I check the ones we have, and if they're ok, go with those?

**Comment by AnnCorp** [comment]
Have already gone back to them just to double-check if any kind of preferred palette, but nothing mentioned in their first email. Think your suggestion to test what's already used is a good starting point (based on Ben's tests on the goal icons, the yellow/mustard colours don't generally pass).

**Comment by shaneporter** [comment]
Changed title based on discussion.
