### ISSUE TITLE
Visualisations for disaggregations

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#19]
AS A user of ONS SDG website
I WANT visualisations of how data for disaggregations compares with data at national level
SO THAT I can quickly/easily see which disaggregated groups are better/worse than national figure and so who is being left behind.
Sample indicators with disaggregated data. In UK system (subject to pull requests going through) try 3.2.2 , 3.4.2 and poss 3.3.1. In US system 8.5.1 and 8.5.2. 
**MVP Requirements**
1.	Some means of selecting a disaggregation from the ones that are available for a specific indicator (will vary between indicators)
query: how handle if no disaggregations – assume just display nothing (or msg saying no dsaggs yet)
2.	Visualisation showing timeseries for each of the various bands within the disaggregation
query: best practice re max number of bands to display, depending on method eg no more than 6 lines on a line graph?
query: what do if only one data point – still generate or not? (should be rare and short-term to have no time series?)
3.	Include the national level as well as the figures for the selected disaggregations
query: how make national figure stand out – need consistent approach
4.	Additional explicit info on visualisations so more in line with ONS standard - Geographic coverage, Units, Source(s) – current US version just links to metadata rather than explicitly including.  This would apply to existing national level charts already in tool. Discuss further if this MVP or beyond.

**General issue**
Data structure – how impacts?? Move to tidy data not current layout – raised by Nathan.
Beyond MVP
1.	Ability to select just one time period and have visualisation for a particular disaggregation for that period.
2.	Would we need to consider nested data – age within sex for example? 

**Disaggregations:**
Taken from http://unsdsn.org/wp-content/uploads/2015/10/151026-Leaving-No-One-Behind-Disaggregation-Briefing-for-IAEG-SDG.pdf
•	Sex and gender
•	Age
•	Income quintiles/deciles, 
•	Location or spatial disaggregation (e.g. by metropolitan areas, urban/rural, or districts),
•	Disability, 
•	Ethnicity and indigenous status, to the extent possible,
•	Economic activity
•	Migrant status, to the extent possible.
Not all disaggregations will apply to all indicators.
As well as these key ones, there may be additonal indicator specific ones.

**Comment by nathaneastwood** [comment]
@shaneporter see the above :)

**Comment by dougmet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User story: visualisations for disaggregations](https://trello.com/c/JhIe5TpX/50-user-story-visualisations-for-disaggregations)

**Comment by dougmet** [comment]
Linking to #41 and #42

**Comment by dougmet** [comment]
We've deployed the first iteration of this with PR #46. We're using indicator 14-1-1 as a demo data set.

**Comment by nathaneastwood** [comment]
Superseded by #152
