### ISSUE TITLE
Guidance on pushing individual changes to master

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1907]
Sometimes need to push individual changes eg to data or one of the non-data pages without doing a bulk push from develop to master and we need guidance on doing this. For example, we currently want to  create and push a new version of the Publications page but don't want to push everything to public site as still have some things to fix re the new  features that are on develop branch.
How could we do this please.? @dougmet  is this a ticket for you please?

**Comment by dougmet** [comment]
https://github.com/datasciencecampus/sdg-indicators/wiki/Urgent-Production-Changes

**Comment by AnnCorp** [comment]
Thanks @dougment.  Re the last para 'These changes must be merged back in to the develop branch, this currently happens by default next time the staging site is released." will we get some extra prompts or info that we need to be aware of  about this when do next release?

**Comment by AnnCorp** [comment]
Doug thinks no changes to main release process
