### ISSUE TITLE
Search not working in IE

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1925]
The indicator search isn't working in on develop or master. Put various words in the indicator search bar and it just hangs showing 'Search results for internet' and not results. Search for the same words in Chrome and it works OK.
I'm on IE 11.0.9600.18816
@shaneporter @gingerbenw  pls could someone look at this as top priority - thank you!

**Comment by dougmet** [comment]
Yes I get a weird popup. No console message.
![image](https://user-images.githubusercontent.com/5878305/33272730-ef87a1de-d382-11e7-9f51-e147aedd6658.png)

**Comment by dougmet** [comment]
It's affecting (old) IOS as well:
This is 
```
Release2015, September
OSiOS, v9
BrowserSafari
Screen Size4.7 in - 2.3 x 4.1 in
Resolution750 x 1334 px
Viewport375 x 667 dp
```

![image](https://user-images.githubusercontent.com/5878305/33273328-df7e711c-d384-11e7-9055-641ca91a8d4c.png)

**Comment by dougmet** [comment]
Fine on latest iOS

**Comment by dougmet** [comment]
The dialogs are a red herring. See #1935 for the issue on those.
