### ISSUE TITLE
Units column incorrectly aligned

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#1929]
A result of the #1873 changes were that 'units' columns were incorrectly aligned right.

Unit column should be left aligned.

**Comment by dougmet** [comment]
This looks good. Quick Q to @AnnCorp . Should the column headers be right aligned as well?

**Comment by shaneporter** [comment]
I took guidance from [this ONS page](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/lf24/lms).

Click 'Table' under the 'Show data as' heading.

**Comment by dougmet** [comment]
ah yes. Consider it merged.
