### ISSUE TITLE
High contrast nav comments

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#1931]
- The accessibility switcher occupies an entire row.  At viewport widths 768px and below, there is a lot of space to the right because the nav collapses. Better to place it here?
- For widths 769px and above, can the accessibility switcher be positioned to the right of the other nav items? Particularly at 768px - 991px, there is a lot of space to the right of the items.
- CSS for `#accessibility-nav` has a display property value of `flex`, which has [limited support on IE](https://caniuse.com/#search=flex).

**Comment by gingerbenw** [comment]
![screen shot 2017-11-30 at 09 47 57](https://user-images.githubusercontent.com/24570483/33426012-5b2d221a-d5b8-11e7-967c-4ea6c9b89ecc.png)
![screen shot 2017-11-30 at 09 48 07](https://user-images.githubusercontent.com/24570483/33426013-5b57077e-d5b8-11e7-91ca-a4b8a77a9225.png)
![screen shot 2017-11-30 at 09 48 14](https://user-images.githubusercontent.com/24570483/33426014-5b7ff328-d5b8-11e7-991c-39401ae67ee8.png)
![screen shot 2017-11-30 at 09 48 21](https://user-images.githubusercontent.com/24570483/33426016-5b997f32-d5b8-11e7-9e6f-0309de969e41.png)

Screenshots for updated header layout

I haven't added the Links onto the end of the existing navigation as this navigation div is hidden on small screen sizes: the alternative of course would be to put the buttons in both locations and hide / show depending on the screen size.

@shaneporter / @AnnCorp - any further thoughts on this or would we be happy with it as it is now?

**Comment by shaneporter** [comment]
The As are still on their own row. It may not be an entire row, pushing everything else (including the logo) down, but it still takes up a lot of space.
