### ISSUE TITLE
'URL' is undefined on IE 9

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1943]
The sub categories do not appear and the error message:

```
'URL' is undefined 
```

Comes out in the console.

**Comment by shaneporter** [comment]
This is because of the line:

```
'href': URL.createObjectURL(new Blob([this.toCsv(table)], {
```

This was previously wrapped in an `if` statement testing for the required object. This `if` statement was removed, but is reinstated by PR #1939.

**Comment by shaneporter** [comment]
But it's still live, so this should remain open until it's verified as fixed. :smile:

**Comment by shaneporter** [comment]
Change made fixing #857 percolated through to this code. We need the check.

**Comment by dougmet** [comment]
I'm not seeing this now. Closing.
