### ISSUE TITLE
IE9: Something missing on selection update

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#1949]
To reproduce, from IE 9 goto: https://datasciencecampus.github.io/sdg-indicators/3-1-2/

Click country->select-all

Console error reads:
```
Unable to get value of the property 'toLowerCase': object is null or undefined
```

I know this is a terrible bug report but IE9 developer tools does not help at all finding where it's tripping over.

**Comment by shaneporter** [comment]
Does the same for 'clear all' too. And all the checkboxes.

**Comment by dougmet** [comment]
Yes, although for `clear all` I get a slightly different console message, which tracks down a failure at event.js: https://github.com/datasciencecampus/sdg-indicators/blob/1fe4241ab764d47f5c3aa4ba5533245e9063aa71/assets/js/event.js#L8

Not sure if this is where the problem is, just where it eventually falls over.
