### ISSUE TITLE
X axis scaling (in addition to existing Y axis scaling)

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#197]
Similar to #187, it would be helpful for the X axis to scale according to disaggregation selections. For example (https://datasciencecampus.github.io/sdg-indicators/3-a-1/) if I selected highest qualification level, and removed the UK line, would if be possible for the X axis min-max to automatically adjust to 2014-16?

Estimate: 4 hours

**Comment by shaneporter** [comment]
The estimate, above, was not good. I have already spent 4 hours on this and am yet to find a solution. 

Revised estimate: 2-3 days.
