### ISSUE TITLE
Add development disclaimer

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#20]
This is publicly visible so we need an appropriate disclaimer about both the data and the site development.

**Comment by dougmet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Produce text for website noting status of data/development](https://trello.com/c/0NVPYk4T/54-produce-text-for-website-noting-status-of-data-development)

**Comment by AnnCorp** [comment]
@shaneporter @dougmet pls could you add text below to home page - it may change again but keen to replace the dummy text asap. Thanks

UK data for Sustainable Development Goal indicators
This is a development website for collecting and disseminating UK data for the Sustainable Development Goal global indicators. This is a collaboration between the ONS Sustainable Development Goals team and the ONS Data Science Campus, building on the earlier work of the US. Currently data on the site may be test data. Please send any comments and feedback to sustainabledevelopment@ons.gov.uk

**Comment by shaneporter** [comment]
Surely it needs to be on **every** page.

**Comment by shaneporter** [comment]
I'll do this on my branch, because Monday is when the website merge is going to occur.

**Comment by dougmet** [comment]
OK, cool. For now the live front page is updated.

**Comment by shaneporter** [comment]
I'm done until Tuesday now @dougmet (last ever commits, to my branch, pushed)

**Comment by dougmet** [comment]
Fixed in d01803f640

**Comment by dougmet** [comment]
From @AnnCorp 
Great idea to put the disclaimer on all the pages. If we're doing that, think we can make the text shorter (and just put a fuller version on some kind of 'About' text when we develop that)

Shortened version below.
This is a development website for collecting and disseminating UK data for the Sustainable Development Goal global indicators. Currently data on the site may be test data. Please send any feedback to sustainabledevelopment@ons.gov.uk

**Comment by shaneporter** [comment]
I've updated this.
