### ISSUE TITLE
Menu and Search misaligned on mobiles

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#2006]
Just noticed from my phone using Chrome that on develop that Menu and Search are misaligned.
MENU appears on one row then the white divider line and SEARCH  appear on row line below.. This doesn't happen on master.
Is this something you can reproduce in Browser Stack? (can't send print screen - my ancient phone is not co-operating...)

**Comment by dougmet** [comment]
![bs_realdroid_mobile_samsung galaxy s4-4 4-1080x1920](https://user-images.githubusercontent.com/5878305/33485234-891f4b7c-d69d-11e7-916d-0c244b2644b5.jpg)

Samsung Galaxy S4 Chrome

**Comment by AnnCorp** [comment]
I'm on an S5 but that's exactly what I see, on develop but not master.

**Comment by dougmet** [comment]
No, same on iPhone 6S

**Comment by shaneporter** [comment]
This can easily be reproduced using chrome's devtools' 'device toolbar'. This is a new issue.

I added a 'subtree modification' breakpoint and saw that the issue is caused by JavaScript. In fact, where are the 'accessibility As'?

**Comment by shaneporter** [comment]
Still an issue, no?

**Comment by shaneporter** [comment]
No. It's not. Sorry. 😊
