### ISSUE TITLE
More than one Filtering box to open at a time 

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#2008]
Instead of only being able to have one filtering box open at a time, want user to be able to control what's open and be able to leave anything open where a subcategory has been selected. Would this involve needing a scroll bar possible?
This cam from discussion with Niren our user research lead plus also from the team when you're using the tool - adds clicks that it autocloses when you've traversing through the categories.
Example Go to 3.2.,1
Under Geography select England and Wales
Go to Sex and select Female
The Geography box  automatically closes but would prefer for Geography and Sex to stay open, showing the selections.

**Comment by shaneporter** [comment]
It won't affect the scrollbar situation. Changing this shouldn't take more than 15 minutes or so.

**Comment by AnnCorp** [comment]
If at all poss be good to squeeze this one in this project (won't add any more non bug stuff, pinky promise!) - we're developing a powerpoint vid showing the features of the tool so be great if this fixed for that.
If not, no worries, it can wait...
