### ISSUE TITLE
Graph key can be hard to read

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#201]
I'm wondering if the key might be better if it didn't display the disaggregation category name e.g. "Bilateral" instead of "Flow of Overseas Development Assistance Bilateral" (https://datasciencecampus.github.io/sdg-indicators/3-b-2/), which is a mouthful!

Alternatively, because it might result unclear distinction between variables for different disaggregation categories, could we add a colon or dash after the disaggregation category? 

Or perhaps we can remove the disaggregation category name but use colour themes to distinguish from different categories? 

Interested to hear everyone's thoughts...

**Comment by MaxEngledew** [comment]
Side note - Alex and I can no longer label issues

**Comment by nathaneastwood** [comment]
Given the changes to the graphics made in b9f00f4, can we say this is now solved @MaxEngledew?

**Comment by MaxEngledew** [comment]
Yep. The text is much better.
