### ISSUE TITLE
The unit of measurement is missing from the tables

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#202]
The can be inferred from the metadata

Estimate: 30 minutes

**Comment by dougmet** [comment]
The field is `computation_units`

**Comment by dougmet** [comment]
I've added the units of measurement under the title for the table. I considered replacing the word `Value` with this value but I'm concerned that it's a free text field and that some of the units are very long.

**Comment by dougmet** [comment]
Reopening for review by SDG team

**Comment by AnnCorp** [comment]
Checked serveral indicators and appearing ok. May review as part of wider QA of page but would cover that in another ticket.
OK to close.
