### ISSUE TITLE
Move global metadata to its own tab

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [datasciencecampus/sdg-indicators#2022]
Related to #212

Where we have one metadata tab we suggest splitting this into two - 'National metadata' (includes how the UK data is calculated) and 'Global metadata'. In the order "National metadata", "Sources", "Global metadata", "Edit".

**Comment by dougmet** [comment]
This is straight forward. 15 minutes.

**Comment by AnnCorp** [comment]
Definitely do in Sprint 11 - will make metadata more visible, has low resource estimate and will fix the bug noted in ticket 1950

**Comment by dougmet** [comment]
Hi @shaneporter , do you have any thoughts on the issue with mobile here?

**Comment by dougmet** [comment]
Closed by #2328

**Comment by norric1** [comment]
Checked - working as expected, although not on IE.

**Comment by shaneporter** [comment]
Hi @norric1 - please could you give details of the version of IE you tested this on? Incidentally, for me, the 'edit' tab appearing below the others, is still there. I'd say the best thing would be to introduce some responsive breakpoints for this.

Also, have some comments on this issue been deleted?

**Comment by AnnCorp** [comment]
@shaneporter From Chris "The table and metadata tabs are not accessible - the URL updates but the display does not. Max tested this and had the same problem."
Not aware of anything being deleted...

**Comment by norric1** [comment]
Hi Shane, I'm using IE11, and have cleared my browser cache. The tabs are there, but I can't select them. I've raised this here: https://github.com/datasciencecampus/sdg-indicators/issues/2348

**Comment by shaneporter** [comment]
Regarding the deletions, I remember uploading a screenshot asking for clarification. Perhaps that was on another issue or PR. Apologies if that's the case.

So, #2335 and #2348 are distinct. Is that correct @norric1?

Thanks :smile:

**Comment by norric1** [comment]
That's correct - https://github.com/datasciencecampus/sdg-indicators/issues/2335 was the exact same problem, but in FireFox (now solved). Unsure if the problem in IE (https://github.com/datasciencecampus/sdg-indicators/issues/2348)is an issue with my system, although Max Engledew reported the same problem when I ran it by him.

Thanks :) Chris
