### ISSUE TITLE
Rename download source button

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#204]
The "DOWNLOAD SOURCE CSV" button should be renamed. It should be something more along the lines of "Download all indicator data: [CSV]" where [CSV] is the button.

**Comment by shaneporter** [comment]
I'm not sure I follow @nathaneastwood - what should the text on the button be? I'm confused by the 

> where [CSV] is the button

comment.

**Comment by nathaneastwood** [comment]
So the button should just have "CSV" written on it. Take this [link](https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthinequalities/articles/healthrelatedlifestylesandwidercharacteristicsofpeoplelivinginareaswiththehighestorlowesthealthylife/june2017) as an example.

**Comment by shaneporter** [comment]
Thanks. So doing a quick devtools edit on that page, you get something like:

![image](https://user-images.githubusercontent.com/2493614/27690952-93f1952e-5cda-11e7-9127-048cf75a5873.png)

**Comment by nathaneastwood** [comment]
Exactly that :) sorry, should have posted that myself really

**Comment by shaneporter** [comment]
No worries @nathaneastwood
