### ISSUE TITLE
Merge indicator numbers and descriptions

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#207]
On the indicator selection page, the indicator number and title should be together. It otherwise implies they are separate things.

Estimate: 0

**Comment by shaneporter** [comment]
I really disagree about this one.

Numbered lists are a common, recognisable feature of written communication, and although the text and number are separated by a visual break, they are still visually associated, particularly when each row's list items are equal in height.

**Comment by nathaneastwood** [comment]
I'm personally in agreement with you @shaneporter. @AnnCorp is this definitely something we wish to change?

**Comment by AnnCorp** [comment]
Think need to consider in tandem with if we're having a mega menu running off 'Statistics' (suggested by Niren) so have some consistency. Suggest we talk through at end of Show and Tell if time or in separate catchup.
