### ISSUE TITLE
Changes to Metadata content & layout

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [datasciencecampus/sdg-indicators#2077]
This ticket covers changes to

- changes to the National Metadata tab eg removing and renaming fields, removing headings
- changes to the Global Metadata tab eg removing fields and removing heading
- change to the Sources tab - remove heading

**Comment by AnnCorp** [comment]
@dougmet here's a Word file with all the changes we're suggesting [National metadata tab - summary of changes.docx](https://github.com/datasciencecampus/sdg-indicators/files/1796826/National.metadata.tab.-.summary.of.changes.docx)

**Comment by dougmet** [comment]
This implies we're removing the `computation` or "How this indicator is calculated" label.

If so then I should probably the title on both national metadata and global metadata

**Comment by dougmet** [comment]
Hi @AnnCorp this missed the Friday release because I want you or @MaxEngledewAdmin to OK before releasing. It's live on the staging site now. If so I can do another Monday morning release to include these changes on live.

**Comment by MaxEngledewAdmin** [comment]
Hi @dougmet apologies for the delayed response - it all looks great. Will this not update live with our next push to master?

**Comment by dougmet** [comment]
Hi Max. This will go live next release.
