### ISSUE TITLE
Add a home page

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#209]
Details to be provided by @AnnCorp

**Comment by AnnCorp** [comment]
Think could very briefly discuss this tomorrow at end of show and tell and if run out of time I'll discuss with SDGs team.  Currently unlikely would have the resource to maintain a home page in the way Niren described it.

**Comment by dougmet** [comment]
Would this be somewhat addressed by enabling the News section?

**Comment by dougmet** [comment]
If we want a certain amount of free text that can be edited in Prose then this could work. Estimate: 4 hours.

**Comment by AnnCorp** [comment]
@14/09 Not planning to include this for sprints pre October publications
