### ISSUE TITLE
Reporting status - change order of categories

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#2093]
At the moment, the order of summary info is 'Exploring data sources', 'Statistics in progress' then 'Reported online' (reflects the order in the original version on US site).
As people read from the left and because the reported online figures are now the greatest for many goals we should reverse the order so from the left we have 'Reported online' 'Statistics in progress' then 'Exploring data sources',.

**Comment by brockfanning** [comment]
@AnnCorp This seemed straightforward enough that I could help out: #2096

**Comment by dougmet** [comment]
Apologies @brockfanning . Holidays etc... I'm reviewing now.

**Comment by dougmet** [comment]
Fixed by #2096
