### ISSUE TITLE
Improved navigation, including targets

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#21]
As a website user
I NEED to easily navigate around the goals/targets/indicators and be clear where I am in the site
SO THAT I can quickly get to the information I need

Feedback from the team re initial US version of system:
•	Would like to improve visibility of which target you’re in when in indicator screens 
•	Would like ability to more easily navigate between the goals, targets and indicators. Currently targets not included anywhere in the navigation and there is no quick, constantly visible navigation tool such as a breadcrumb bar.

@shaneporter @dougmet @nathaneastwood pls advise how want to take this forward - discuss options w/c 13/02 and produce more detailed reqirements from there?

**Comment by AnnCorp** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User story: improved navigation, including targets](https://trello.com/c/QkC71OHs/55-user-story-improved-navigation-including-targets)

**Comment by nathaneastwood** [comment]
@shaneporter is this clearer now? Did you add the target to the top of the coloured field when you click on an indicator? Or is that the goal description?

**Comment by nathaneastwood** [comment]
Ok, I just looked at the current iteration. @AnnCorp when you click on an indicator, it shows the goal description as well as the indicator description at the top (in the coloured section). Would including the Target text in here be a solution?

**Comment by dougmet** [comment]
Goals and targets data added to Trello ticket.

**Comment by dougmet** [comment]
[Goals targets and indicators.xlsx](https://github.com/ONSdigital/sdg-indicators/files/766722/Goals.targets.and.indicators.xlsx)

**Comment by AnnCorp** [comment]
@nathaneastwood think that's the obvious solution to try first though with the lengthy text descriptions not sure how it will all fit in?!

**Comment by shaneporter** [comment]
It can fit in of course, but I think the design of the site needs to change. I'll give it some thought.

**Comment by nathaneastwood** [comment]
These issues are relevant to #151
