### ISSUE TITLE
Multiple units of measure

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#223]
We need separate pages for 9.2.1 per capita and 9.2.1 % of GDP

Estimate: 6 hours

This estimate is based on a bespoke fix where `Units` is a special column name that indicates multiple datasets in one csv.

**Comment by AlexLewis1** [comment]
We will need separate pages for indicators 8.4.1, 8.4.2, 8.9.1, 8.10.1,12.2.1, 12.2.2, and 12.c.1 as they all have two separate units of measure.

**Comment by nathaneastwood** [comment]
If this is going to be more common, which it seems it is, then we maybe need to consider a more effective way of displaying this. @dougmet and @shaneporter can you think of a good way to do this?

Shane, for some background: Indicator 9.2.1 has two key ways of measuring the indicator: per capita, and % of GDP. Displaying them together doesn't really work, unless we were to start having dual axes, since they have such different scales.

@AlexLewis1 and @MaxEngledew does the new filtering system help in anyway? Looking at 9.2.1 I can now select the headline indicator individually so I no longer get a massive gap between the two lines. Of course, we still cannot easily compare them but I imagine we could fix this with a dual axis and some form of metadata `dual_axis: Headline indicator`.

**Comment by MaxEngledew** [comment]
The filtering certainty helps with the y axis scaling on this indicator.

With regards to a long term solution its a question of weighing up the benefit of being able to compare the two headlines (which will have to be on an indicator basis) against not having an immediate headline visualization appear (a default empty graph) which is probably more important to the general public. Is there a way one of the headlines could be ticked as a default?

**Comment by nathaneastwood** [comment]
We could probably easily add a metadata field that would give you the ability to select an option for the headline to show as a default.

**Comment by MaxEngledew** [comment]
That would be a nice enhancement - although if we do follow that route we will need dual axis, which I understand will require many other enhancements (more metadata fields etc). I wonder if still the simplest solution is adding more indicator pages although you're in a much better position to judge the workload of these options?

**Comment by AnnCorp** [comment]
Discussed possible workaround of separating out the indicators (eg 9.2.1a and 9.2.1b) but this would impact on figures on reporting status page. 
For SDG team to discuss in more detail ahead of Sprint 7 how take this forward.

**Comment by AnnCorp** [comment]
From Max, other examples: 
So the Sendai framework related indicators come to mind (1.5.3,11.b.1, 13.1.3)
But the one I was specifically asking about was 9.1.2 - we're not sure how to format our csv.
also 4.1.1 and 4.6.1

**Comment by MaxEngledew** [comment]
I'm working on building a more definitive list of indicators where this is the case - though this list could grow as the UN add/update metadata.

**Comment by dougmet** [comment]
I've changed the name of the special column to `Units`

**Comment by MaxEngledew** [comment]
Thanks - we'll put them under that from now on!

**Comment by MaxEngledew** [comment]
@dougmet How does it/will it pick the default? Is this something we can choose ourselves through the layout of the csv?

**Comment by dougmet** [comment]
Good point @MaxEngledew, I'm not totally sure yet but I'd guess it'll be in order that they appear.

**Comment by dougmet** [comment]
Fixed in ffc2cf7ffe13eec3bd27cbd98322f8d2552aae98
