### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#2250]
Top level diagram of the build process

**Comment by AnnCorp** [comment]
@dougmet could you give  an estimate on this please - will be useful for us communicating with other countries hoping to copy our system, but can't allocate much time to it. Cheers!

**Comment by dougmet** [comment]
A screen grab version is on the wiki https://github.com/datasciencecampus/sdg-indicators/wiki/Architecture and pptx is attached here. Is this about the right kind of level or more/less detail?
[sdg-architecture.pptx](https://github.com/datasciencecampus/sdg-indicators/files/1719369/sdg-architecture.pptx)

**Comment by AnnCorp** [comment]
@dougmet I think this about the right level of detail, though may need to expand a few points a little to make clearer to those less techy. I'll edit/comment on a version of the Powerpoint .

**Comment by AnnCorp** [comment]
Ann still to do this -  after today out of office until 28 Feb so will try to look at it then.

**Comment by AnnCorp** [comment]
@dougmet am happy to close this one and leave diagram as-is for now.
