### ISSUE TITLE
The change_configs script fails when given inappropriate parameters

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#231]
Only the `_config.yml` file contains information on the country (name and adjective) so if passing a these arguments to `_config_staging.yml` or `_config_prod.yml`, the user is presented with an error. This should soft fail and provide a warning instead. In other words the following code works only for `_config.yml`

```
python3 ./change_configs.py -f ../_config.yml -n TEST -a TEST
```

Estimate: 15 mins

**Comment by dougmet** [comment]
@nathaneastwood we will remove the unused staging and prod configs for now

**Comment by nathaneastwood** [comment]
Sure. I'll update the Wiki too.
