### ISSUE TITLE
Update icon for Goal 10

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#2326]
We need to update the icon for goal 10 as the design has changed - colour version and B&W attached below.
<img width="1000" alt="theglobalgoals_icons_black_goal_10" src="https://user-images.githubusercontent.com/24583831/36204724-58aaa028-1184-11e8-9847-8a1a803d3f0a.png">
<img width="1000" alt="theglobalgoals_icons_color_goal_10" src="https://user-images.githubusercontent.com/24583831/36204725-5a274492-1184-11e8-99e2-8fba4a0a0f54.png">

**Comment by AnnCorp** [comment]
@dougmet @shaneporter is this a v quick job?

**Comment by shaneporter** [comment]
Hi @AnnCorp - it's v quick :)

**Comment by dougmet** [comment]
Just realised that we need to update the colour list in the styles to match this. Should have picked that up before merge. Doesn't require a revert but we just need to update the style sheet @shaneporter .

**Comment by shaneporter** [comment]
PR #2334

**Comment by norric1** [comment]
Checked - worknig as expected for both colour schemes.
