### ISSUE TITLE
Indicator 2.5.2 not displaying

### ISSUE THREAD

**Issue by norric1** [datasciencecampus/sdg-indicators#2327]
Indicator 2.5.2 is not displaying on the tool, but has passed the GitHub checks.
No whitespace, or other syntax errors as far as we can see. This might be a hierarchy issue as there are three data columns and no headline data.

Thanks,
Chris

**#2324 
#2303**

**Comment by dougmet** [comment]
OK thanks. Can't see it on first pass. There are some commas in the text but they all look quoted.

**Comment by shaneporter** [comment]
The issue relates to the Barbu D'Anvers (a Belgian Bantam, apparently) breed.

Its apostrophe is causing issues in the (html) source. I remember there was a similar issue with another indicator a while ago, but can't recall which one it was.

**Comment by norric1** [comment]
Shane,

Excellent, thanks for your help on this.

Chris

**Comment by shaneporter** [comment]
hi @norric1 - if the apostophe's been removed, I can close. Please let me know. Thanks.

**Comment by norric1** [comment]
Close please.
