### ISSUE TITLE
Incorrect edges on 8.5.2

### ISSUE THREAD

**Issue by brockfanning** [datasciencecampus/sdg-indicators#2330]
Indicator 8.5.2 shows "Sex" as a parent of "Disability status", but there is no data in the "Disability status" column. I've got a possible fix that I'll submit as a PR.

**Comment by dougmet** [comment]
Great, thanks @brockfanning . This fixes that issue. I wonder if empty columns are a good idea. @MaxEngledewAdmin would it be good to block this in the build checks as well as this change here?
