### ISSUE TITLE
NRP clone trial

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [datasciencecampus/sdg-indicators#2340]
Hi - I've cloned the NRP - https://maxengledewadmin.github.io/sdg-indicators/ (up to date as of 19/02/2018) https://github.com/MaxEngledewAdmin/sdg-indicators. This issue is a placeholder for discussion in the forthcoming sprint. 

Noticed a few of things - in no particular order:

1. Despite being identical to the develop NRP, the indicator pages are displaying differently ([Max](https://maxengledewadmin.github.io/sdg-indicators/3-1-2/)/[Develop](https://datasciencecampus.github.io/sdg-indicators/3-1-2/))
2. Basic edits such as the [front page text](https://github.com/MaxEngledewAdmin/sdg-indicators/commit/a4df133e675c6f05e3e9b40f669c51a29e3f7310#diff-3d43a859b89befcff236477b6c724325) are [failing ](https://travis-ci.org/MaxEngledewAdmin/sdg-indicators/builds/343800331?utm_source=github_status&utm_medium=notification)
3. Prose still seems to editing/linking to develop - I don't think there was anything in the guidance to change this
4. Some links in [this guidance](https://github.com/datasciencecampus/sdg-indicators/wiki/What-do-we-need-to-change) are broken 
5. There's little information on the need and how to create a local repository for running scripts

**Comment by dougmet** [comment]
Hi Max, thanks for this. I'll address these and the documentation and step through the process myself.

**Comment by dougmet** [comment]
Today I'm stepping through the clone process for myself. Known changes that need to be made for a full copy:

1. Clear data
2. Clear metadata
3. Check site variables in `config.yml`
3. Change/clear google analytics
4. Activate Travis build
5. Setup Travis deploy (this is the most advanced)

**Comment by dougmet** [comment]
I've stepped through changing data, metadata, and also the config #2360. Should be able to build local from here

**Comment by dougmet** [comment]
One note that rather snuck up on me. The repo has swollen to about 580Mb, which makes cloning slow. It's not a big deal, I think it's related to the way we're using the `gh-pages` branch for serving. I don't see an easy work around in the short term.

Otherwise, I've cloned, reset, and built locally without any major issues.

![image](https://user-images.githubusercontent.com/5878305/37038070-ad66cd72-214b-11e8-8ccb-b4b7ada3d5e9.png)

**Comment by AnnCorp** [comment]
@dougmet think you could close this issue now? Is there anything you want to add into the ticket for completeness? Will leave it to you to close it...

**Comment by dougmet** [comment]
Yes let's close. If we need further documentation changes let's make small tickets.
