### ISSUE TITLE
Update clear data script

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#2352]
There's an existing script that is probably OK. Just want to check that it's up to date:

`scripts/reset/reset_csvs.py`

relates to #2340

**Comment by MaxEngledewAdmin** [comment]
@dougmet  I've just tried this and encountered errors

`File "reset_csvs.py", line 46, in <module>
   reset_csvs()
 File "reset_csvs.py", line 20, in reset_csvs
   if not os.path.exists(file):
NameError: name 'file' is not defined`

**Comment by dougmet** [comment]
Yes this script was not functioning correctly, I think I've fixed it now.
