### ISSUE TITLE
Lazy load data

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#2367]
Breaking away from a discussion about data size on #2297 so that I can have a chat with @shaneporter about how we load the data. 

### Today
The data is serialised into JSON and embedded in the html page. Some of the data sets are getting big (~8Mb in csv and 15Mb in html) and this makes the page slow to load. My experience is that the top of the page loads OK but then the metadata has to wait for all of the data to fill in.
### The future
A service will provide and API to get just the data you need.
### In between
As a stop gap solution can we think of ways to improve page loads when the data is big? I had two thoughts:

1. Move the JSON right to the very bottom of the html file so that the metadata loads.
2. As part of the build we could put the JSON in separate files, rather than embed it, and then you can send a request for it and render the chart when it arrives.
3. Same as 2 but we leave the headline data on the page so that we can quickly show a chart.

Any thoughts @shaneporter?

**Comment by shaneporter** [comment]
If you're able to do item 2 without too much hassle, then I can carry on from there.

Without JavaScript, the embedded data is still loaded anyway, but is completely wasted since it's not used at all. So, let's split out into a separate JSON, then make an asynchronous request for the data. That way, non-JS users get everything really quickly, and JS users get everything but the data really quickly, with some UI feedback that the data is loading.

**Comment by brockfanning** [comment]
Just in case it's helpful, something similar has just been merged into the US platform. The idea was to add a level of abstraction on top of the injection of the data, to allow for the possibility of getting data from a source other than local CSV files (such as an external API). The mechanism was a swappable "indicator data source", implemented by a Jekyll include. The entry point is [this spot in the indicator layout](https://github.com/GSA/sdg-indicators/blob/gh-pages/_layouts/indicator.html#L220). It first pulls in a [common base](https://github.com/GSA/sdg-indicators/blob/gh-pages/_includes/indicator_data_source/base.html) and then the particular data source, determined by a front-matter flag `indicator_data_source`. So far, there is only one possible data source, the [local csv file](https://github.com/GSA/sdg-indicators/blob/gh-pages/_includes/indicator_data_source/local_csv.html). Currently that local_csv data source actually embeds the data into the markup, but it could also have grabbed the CSV data with a javascript-based request. The idea is that each "indicator data source" would implement several functions to adapt the data to a visualization function, like [this one for bar graphs](https://github.com/GSA/sdg-indicators/blob/gh-pages/_includes/components/bar.html#L8).

**Comment by dougmet** [comment]
Yes dumping the JSON is straight forward enough. Do you want headlines and edges as well?

**Comment by shaneporter** [comment]
Yes please :+1:

**Comment by dougmet** [comment]
Hit comment without refreshing. Thanks @brockfanning, this is exactly the sort of thing we're thinking about at the moment.

**Comment by dougmet** [comment]
separate files? @shaneporter Sorry, being inefficient with questions today.

**Comment by shaneporter** [comment]
No worries at all. Yes, separate files would be great, thanks.

**Comment by dougmet** [comment]
Hi @shaneporter I've added gzipped json files into the build process with `scripts/build/build_json.py` in branch e/2367-json. It creates json files with data and edges for each indicator.

```
├───data
│    ├───edges
│    ├───headlines
│    └───json
│         └──indicator_1-1-1.json.gz
```

The format is currently columner, or "list" so it looks like this:

```json
{
  "data": {
    "Year": [2015, 2015, 2015, 2016, 2016, 2016],
    "Group": ["A", "B", null, "A", "B", null],
    "Value": [1, 3, 2, 1, 3, 2]
  },
  "edges": []
}
```

I can switch this to `records` or row-wise easily as it's an option in the python script. The reason I like list is that it writes out much less text as records has to write the column name in every row.

The file compression is huge so if you're able to read the gzipped versions this will be well worth it. For example for 4-2-1 the file sizes are as follows:

| Orient | Compression | Size | 
|:--------|:---------------|-------:|
| records | None | 16,796 KB |
| list | None | 7,691 KB |
| records | GZIP| 416 KB |
| list | GZIP | 139 KB |

Let me know if any problems. Reading the binary versions.

**Comment by dougmet** [comment]
Edges is also columnar. Sorry if that's a problem.

**Comment by shaneporter** [comment]
The bog-standard jquery ajax request will have the following header:

`Accept-Encoding:gzip, deflate, br`

And web servers supporting compression will gladly respond with this header:

`Content-Encoding: gzip`

GitHub pages should be very happy to do so.

What this means is that the files themselves don't need to be compressed by the script - the web browser will compress them, and the client will decompress them, all transparent to the user, and with big big savings!

So, I should be able to just request the JSON resource, and I'll get the compressed version automatically.

**Comment by dougmet** [comment]
ah OK, will remove the gzip part then.

**Comment by shaneporter** [comment]
The `Accept-Encoding` request header is there already.

It appears that the local jekyll server, WEBrick, doesn't include the  required `Content-Encoding` response header, but the GitHub pages will, so that's all good.

**Comment by dougmet** [comment]
Hi @shaneporter Anything left from you or do we merge #2579 ? Maybe give it a robust local test first.

**Comment by shaneporter** [comment]
I'm going to simulate some network latency and see if there are some UI improvements to be made whilst in the 'loading data' stage.

**Comment by dougmet** [comment]
Oh I like the loading icon
