### ISSUE TITLE
Add a scroll bar to the graph filtering dropdowns

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#240]
Some of the dropdowns contain a lot of disaggregations and so could do with their own scroll bar which is separate to the page scroll bar. Take the "Sub category of manufacturing" drop down as an example in [this](https://datasciencecampus.github.io/sdg-indicators/9-2-1/) indicator.

**Comment by MaxEngledew** [comment]
Could we also add a select all function?

**Comment by nathaneastwood** [comment]
Good question - one for @shaneporter

**Comment by shaneporter** [comment]
That's something that can be done, yes.

**Comment by dougmet** [comment]
Child of #129

**Comment by AnnCorp** [comment]
Poss Sprint 7 or later- to be discussed if

**Comment by MaxEngledewAdmin** [comment]
@dougmet This seems to still be an issue - [10.b.1 (select Aid description)](https://datasciencecampus.github.io/sdg-indicators/10-b-1/)

**Comment by shaneporter** [comment]
On a slightly different note, I thought there was a bug with the 'Aid description' on 10.b.1.

I wasn't seeing checkboxes for all the items and had _no idea whatsoever_ that this was because there wasn't any data. (I only saw 'no data' because I inspected the items).

My point is that how will a user know it's because there is no data?

**Comment by MaxEngledewAdmin** [comment]
The checkboxes in "Aid description" are dependent upon a unique combination of "Aid Sector", "Aid Category", and "Aid Subcategory"  - its a horribly complex hierarchical  data set full of inconsistencies... 10.b.1 definitely breaks the filtering

**Comment by AnnCorp** [comment]
@MaxEngledewAdmin is going to have a closer look at the data and the logic for 10.b.1 as it is so complex.
It won't fall into the current sprint to look at
