### ISSUE TITLE
10.b.1 Graph not appearing

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#243]
Added data for 10.b.1 (#233) - but graph doesn't appear to be loading. Other data uploads (e.g. #242), which were also committed 17/07/2017, seem to have worked fine.

**Comment by nathaneastwood** [comment]
@shaneporter the console errors are

```
Uncaught Error: Syntax error, unrecognized expression: :checkbox[value="""][data-field="0"]
    at Function.fa.error (jquery-1.12.4.min.js:2)
    at fa.tokenize (jquery-1.12.4.min.js:2)
    at Function.fa [as find] (jquery-1.12.4.min.js:2)
    at n.fn.init.find (jquery-1.12.4.min.js:2)
    at sdg.js:444
    at Function.m.each.m.forEach (underscore-min.js:5)
    at sdg.js:443
    at Function.m.each.m.forEach (underscore-min.js:5)
    at Array.<anonymous> (sdg.js:442)
    at event.notify (sdg.js:18)
jquery-1.12.4.min.js:2 Uncaught Error: Syntax error, unrecognized expression: :checkbox[value="""][data-field="0"]
    at Function.fa.error (jquery-1.12.4.min.js:2)
    at fa.tokenize (jquery-1.12.4.min.js:2)
    at Function.fa [as find] (jquery-1.12.4.min.js:2)
    at n.fn.init.find (jquery-1.12.4.min.js:2)
    at sdg.js:444
    at Function.m.each.m.forEach (underscore-min.js:5)
    at sdg.js:443
    at Function.m.each.m.forEach (underscore-min.js:5)
    at Array.<anonymous> (sdg.js:442)
    at event.notify (sdg.js:18)
```

**Comment by nathaneastwood** [comment]
@MaxEngledew I am just looking at the actual csv file for this indicator and for a large chunk of the file there are no data in the "Value" column.

**Comment by MaxEngledew** [comment]
Oh right. Apologies, I'll fix and re-upload.

**Comment by nathaneastwood** [comment]
@dougmet we may need to consider how this affects non-statistical indicators?

**Comment by MaxEngledew** [comment]
A side point - Hopefully its just my pathetic laptop but the I'm crashing quite a lot trying to upload data for 10.b.1 -  seems like you can just wait it out though. 
![example](https://user-images.githubusercontent.com/24583650/28308832-5a6684c6-6b9f-11e7-8ddf-5c37764acb15.png)

**Comment by nathaneastwood** [comment]
So it eventually worked? We need to get you using command line `git` ;)

**Comment by MaxEngledew** [comment]
@nathaneastwood Yea, it worked eventually. That would be good! 

Just concerned that, if this will reoccur for large data-sets in prose, it may impact the international capacity of the tool. Is it possible to add a reassuring "this may take a while - please wait" message?

**Comment by nathaneastwood** [comment]
Yes I agree. Not sure if this is a prose issue or related to your laptop.

The graph still doesn't appear to be showing for me. I will investigate further.

**Comment by dougmet** [comment]
@nathaneastwood I think non-statistical indicators will need a flag so that it doesn't try to plot a graph. We already have `graph_type` which isn't used. We can either have an on off switch or `graph_type: none` for example.

If there are errors in the value field that cause the graph not to plot I'd like this to be picked up in the build so might need to look at that.

**Comment by nathaneastwood** [comment]
`graph_type: none` seems the most sensible. Rather than `on` or `off` because there will be a need for other graph types. Particularly as people start to integrate mapping tools.

**Comment by dougmet** [comment]
also, `graph` and `graph_type` need merging (ie get rid of `graph`). Making a ticket...

**Comment by MaxEngledewAdmin** [comment]
@dougmet This seems to have happened again with #422

**Comment by shaneporter** [comment]
Yep, this is because of a JS error, which can be seen in the console:

```
Uncaught Error: Syntax error, unrecognized expression: :checkbox[value="""][data-field="0"]
```

That `value` isn't correct (its an invalid string), but I'm not sure where it's coming from. Will investigate, but if it's not happening elsewhere, it's possibly a data issue or edge case.

**Comment by shaneporter** [comment]
Cote d'Ivoire is causing us an issue.

**Comment by MaxEngledewAdmin** [comment]
Oh right - we'll switch it to `Ivory Coast`

**Comment by shaneporter** [comment]
Thanks - although there _may_ be another issue too, but I'll take a look.

**Comment by MaxEngledewAdmin** [comment]
We've removed all superscript from 17.9.1 #459 - doesn't seem to have fixed the issue
