### ISSUE TITLE
Raw Metadata in Prose

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#247]
Bulk wipe all of the raw metadata from prose - as its all US specific.  Even if this meant wiping all metadata entirely I still imagine it would be quicker to re-upload these than to manually remove all raw metadata from prose.

Estimate: 45 minutes

**Comment by dougmet** [comment]
I'm going to write a script to do this.

**Comment by dougmet** [comment]
nearly there. Just worrynig about some fields that we never explicitly added to prose, and what `NULL` should look like in the output
