### ISSUE TITLE
Reporting status - iteration of dummy data

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#248]
Currently, the Reporting Status page is based on dummy, random data, generated by JavaScript for the 'Exploring data sources', 'Statistics in progress' and 'Reported online' statuses.

As an iteration for this area of functionality, it would be useful to add a metadata key/value representing 'reporting status' for each indicator, and then generate the data off these statuses. Although the statuses will be random, the code will be there so that when they are set according to the indicator's status, the data will be shown accordingly.

Estimate: 90 mins

**Comment by dougmet** [comment]
Could you put in a list of allowed statuses so I can add it to the Prose config:

**Comment by shaneporter** [comment]
Example line in .md: 

```
reporting_status: complete
```

the possible values are: 

`notstarted`, `inprogress` and `complete`.

**Comment by dougmet** [comment]
Closing because the branch already got merged. #273 is now where this lives.
