### ISSUE TITLE
Sort graphics metadata

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#250]
Currently we have a lot of redundant graphics metadata that should be removed. The ones I am aware of<sup>1</sup> are as follows:

In the `_config*.yml` files:
- `graph_type`
- `graph_title`
- `data_edge_list`

In the metadata `.md` files:
- `graph_type_description`
- `graph_status_notes`
- `graph`
- `graph_title`
- `graph_type`

<sup>1</sup> not all of these may be redundant

Estimate: 30 mins

**Comment by dougmet** [comment]
This ticket is related to #277 . `graph_type_description`, `graph_status_notes` have been removed in PR #276 . `data_edge_list` can go once we know that it's not going to be used

**Comment by AnnCorp** [comment]
@dougmet could you clarify what of the original issue still needs to be done pls and when (if links to #285, is it for Sprint 6?). Cheers

**Comment by dougmet** [comment]
`graph` will be be removed. `graph_type` will be one of `line` or `bar`, and if others want adding then they need to be explicitly added in `_config.yml` and `chart.html`. Will be closed by #285
