### ISSUE TITLE
URGENT - NRP indicator graphs/charts not displaying

### ISSUE THREAD

**Issue by norric1** [datasciencecampus/sdg-indicators#2534]
We have been updating the metadata on the NRP tool, and although most of them have updated as expected, some of the indicator graphs (3.4.1, 3.8.2, 15.2.1) are now not displaying. The data is definitely present, as the data tables work, and CSVs can be downloaded.
e.g. https://datasciencecampus.github.io/sdg-indicators/15-2-1/

Can you advise please? I am happy to provide a full list of indicators not displaying. The deadline is coming up soon, so the sooner this can be resolved the better.

Many thanks,
Chris

**Comment by dougmet** [comment]
Sorry I missed this. It looks like neglect may have worked -- perhaps another bugfix worked? Is there a way to reduce the `unit of measure` in 3-4-1 btw?

**Comment by norric1** [comment]
Thanks Doug, you helped us with this already - last week.
Good call - 3.4.1 updated!

Cheers,
Chris

**Comment by dougmet** [comment]
Smashing, will close then.
