### ISSUE TITLE
Add sources 4 & 5 display functionality [MUST FIX]

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [datasciencecampus/sdg-indicators#2564]
Occasionally indicators will require more than 3 sources, we need functionality for 2 additional source 'slots'

**Comment by AnnCorp** [comment]
Example indicators with lots of sources are 9.5.1, 1.a.2 and 4.1.1

**Comment by dougmet** [comment]
Sure. 6 it is. This is a quick change.

**Comment by AnnCorp** [comment]
@norric1 @MaxEngledewAdmin  pls could you have a look at this and check you're happy with it. Cheers!

**Comment by dougmet** [comment]
This is looking done to me. The issues with the new metadata were due to:

1. Files copied to wrong location
2. Wrong character encoding (must be UTF-8). Watch out for things like smart quotes etc.
