### ISSUE TITLE
Format line breaks in metadata fields

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#2570]
Some metadata fields go across multiple paragraphs. The line breaks are of course ignored by html.

It would be nice if the paragraphs could be properly detected and formated, either with line breaks or `<p>` tags

**Comment by norric1** [comment]
Hi Doug, we had success with two <br><br> tags - this creates a paragraph in the text.

**Comment by AnnCorp** [comment]
Looks like this one can be closed.
