### ISSUE TITLE
Out of scope geographies

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#2590]
We need to distinguish between missing data and data that's out of scope. For example, in 4-2-1 the data is only for England, so Scottish/Welsh LADs wouldn't have data. However, English LADs should be shown as blank.

Out of scope: Same as background colour
Missing: White

Now ONS geography codes are nicely structured. I propose to use a `geocode_regex` metadata field so that we can specify this. For countries wanting to clone the site they will either not have the complication of multiple countries in a country, or they can use the regex for their own codes. Or submit a PR ;-)

In this case the code would be something like `geocode_regex: ^E` to pick up all English codes.

**Comment by shaneporter** [comment]
From #2297, 'white' is rgb(240, 240, 240).

**Comment by shaneporter** [comment]
So they still want to see Wales and Scotland, but LADs in those countries should have the following characteristics:

1. no hover tooltip
2. no hover state
3. no click/zoom
4. transparent colour

Any LADs that match the regular expression but have no data will have an rgb(240, 240, 240) background colour.

The current background of the map is currently rgb(238, 238, 238), so I'd best change that as it's pretty close to rgb(240, 240, 240).

**Comment by dougmet** [comment]
Did I add the metadata field? If not I will.

**Comment by shaneporter** [comment]
I've done it.

One thing though, I'm wondering whether out-of-scope LADs should actually be shown at all.

**Comment by shaneporter** [comment]
I've not implemented no. 1 nor no. 2, since it may be useful to still see the names of areas that are out of scope (since they're being shown after all.)
