### ISSUE TITLE
Control when maps appear using metadata

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#2603]
@shaneporter @dougmet  Need to be able to control if show map rather than automatically show them if detect geo codes. This is because we need to be adding geo codes to data as soon as poss (best practice) and before we will have been able to fully develop the maps for all boundaries etc.
Doug suggested could have some kind of flag/checkbox in the metadata (default is no but we could set to yes) and that maps are generated if detects geocodes and this field is checked.
Doug confident can fit this into Sprint 13

**Comment by dougmet** [comment]
I will add a `data_geography_show_map` field with a check box

**Comment by dougmet** [comment]
Hi @shaneporter, I've started this in branch `e/2603` and have added my bits. If you're flat out today I'll go into the JS. Essentially we want to change the condition for drawing the map from: "Is their a GeoCode" to: "Is there a GeoCode AND show_map=True"

**Comment by shaneporter** [comment]
Hi @dougmet - I'll take a look at this. Cheers!
