### ISSUE TITLE
Boundaries for 3-9-1 not matching

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#2606]
Hi @Norric1Admin the map for 3-9-1 isn't working https://datasciencecampus.github.io/sdg-indicators/3-9-1/

My best guess is that the GeoCodes are not lining up with what we have in the LAD data set.

We're using the ultra generalised LAD boundaries. I think it's 2017 so please look here for the available codes and feedback if that's the issue or if it's something else.

http://geoportal.statistics.gov.uk/datasets/local-authority-districts-december-2017-ultra-generalised-clipped-boundaries-in-great-britain/data

Thanks

**Comment by Norric1Admin** [comment]
Thanks Doug. The codes are definitely using the correct LA boundary - I'm an having trouble getting the CSV to pass the checks though. Also, the CSV contains Region boundaries which might be confusing things, although wouldn't the map ignore the codes it doesn't recognise?

Chris

**Comment by Norric1Admin** [comment]
Hello Doug, could you advise on why https://github.com/datasciencecampus/sdg-indicators/pull/2610 has failed please?

**Comment by dougmet** [comment]
Hi, the files have gone into the root directory instead of the data directory.

**Comment by dougmet** [comment]
Latest one was because the last column has to be `Value`. This restriction is a little ott because the code only cares if the `Value` column exists, not where it is. It's just that I don't have time to change that check in the short term.

Plus it's prettier having Value at the end, easier to read and more consistent for users.

**Comment by dougmet** [comment]
Hooray!

![image](https://user-images.githubusercontent.com/5878305/38091054-4796b642-335c-11e8-8263-67dcd6938eb3.png)

**Comment by Norric1Admin** [comment]
Thanks for your patience - easy when you know how! The latest one has passed :)
