### ISSUE TITLE
Merge graph and graph_type metadata

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#277]
These are nearly copies of each other but both appear to be used.

We should keep `graph_type` and remove graph, but check the following:

1. Existing data in `graph` should match what's in `graph_type`
2. Check `_includes\components\charts\line.html` which uses both
3. Check lowercase or Capitalcase

**Comment by AnnCorp** [comment]
@dougmet do we need this issue in Sprint 6 if its linked to 285?
