### ISSUE TITLE
Metadata not feeding through to live site [1.5 hours]

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#285]
Since the removal of US metadata we've lost some titles. The title should come from the `graph_title` metadata field.

Relates to #250 and #277

**Comment by MaxEngledew** [comment]
I believe we're also having a similar issue with Units of Measurement feeding into the y axis.

**Comment by AnnCorp** [comment]
Example of this issue from Max: 
3.2.1 
Graph title in metadata is " Mortality rate for infants and children younger than 5 years old per 1,000 live births "
and Units of measure in metadata is "Number of deaths per 1,000 persons"
neither is feeding through to the graph
