### ISSUE TITLE
Unreported indicators (inc suppressing graph) [est 3hrs]

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#286]
For indicators that have no data we want to remove the boiler plate data. However, there are a few things we should do in that instance:

1.	Set reporting status to notstarted.
2.	Tell the website not to display anything that’s notstarted or inprogress(?).
3.	Decide what we *do* show for indicators that are not started (e.g. UN metadata etc)

Bulk edit the csvs for unreported indicators.

I’m tempted to leave the empty csv files as they make it easier to add data. We can remove the data and just leave the headings in if that is better. The main point is that we have a flag that can essentially switch off an indicator.

Tasks:

- [ ] Add a non-statistical flag in metadata (suppresses graph and table)
- [ ] Do not show graph or table for indicators that do not have status `complete`

**Comment by dougmet** [comment]
In the first instance I'm setting all reporting statuses to `notstarted`. @MaxEngledew and @AlexLewis1 can assist on switching the ones we've done back to `completed` or `inprogress`

**Comment by MaxEngledew** [comment]
For now can we switch the list below to `completed`:
2.a.2
3.2.1
3.2.2
3.a.1
3.b.2
5.2.1
5.2.2
5.4.1
5.5.1
6.a.1
8.1.1
8.2.1
8.5.2
8.9.1
8.a.1
9.2.1
9.a.1
10.b.1
11.7.2
11.c.1
15.a.1
15.b.1
16.2.3
17.8.1

And these to `inprogress`:
1.2.1
1.2.2
1.4.2
1.a.2
2.3.2
2.a.1
3.1.2
3.3.1
3.3.3
3.4.1
3.4.2
3.5.2
3.6.1
3.7.2
3.c.1
4.2.2
4.3.1
4.b.1
5.5.2
6.3.2
6.5.1
6.5.2
7.1.2
7.3.1
7.a.1
8.4.1
8.4.2
8.5.1
8.6.1
8.8.1
9.2.2
9.4.1
9.5.1
10.2.1
11.6.2
12.2.1
12.2.2
16.1.1
16.1.2
16.1.3
16.1.4
16.3.2
17.1.1
17.1.2

Thanks Doug, we'll make sure to update this field as we add indicators.

**Comment by dougmet** [comment]
OK that's done. The reporting status should now be **correct**. Submit relevant pull requests for any problems spotted.

This ticket needs to remain open because it's main issue was suppressing output for unreported indicators. Is it your understanding that only indicators that have `complete` as a reporting status should show any data?

**Comment by MaxEngledew** [comment]
Yes - only `complete` indicators will show data. 

Related though - there will be `complete` indicators which are non-statistical and therefore won't have data or need for a chart. Is there ways the tool could distinguish between these in order to auto remove any chart from displaying?

**Comment by dougmet** [comment]
I think a `graph.show` flag could be useful for this.

Would non-statistical indicators have tabular data?

**Comment by MaxEngledew** [comment]
Not sure - there's a possibility that we might use a table for some sort of annual met/not-met classification but I was always under the impression that the implementation of a 'catch all' box would be enough for the nonstat indicators. I think there's still some discussion to be had around exactly what we do with them @AnnCorp
