### ISSUE TITLE
Investigate: remove CSV-based JS from site

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#29]
After doing some work to convert CSV to JSON in the Jekyll output, it now doesn't seem necessary to import a JavaScript 'CSV' library or use the `csvToHtmlTable.js` script.

Remove these dependencies.

**Comment by shaneporter** [comment]
The key point here is that the CSV will remain, since that should be available for download, but that there is no need to work with CSV when we can easily use the CSV's JSON equivalent.

**Comment by dougmet** [comment]
Can this now be closed?

**Comment by shaneporter** [comment]
Not yet. I will take a look at some point and close it.
