### ISSUE TITLE
Commits not going through to live site - can't 'Merge'

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#306]
SDG team don't get option to Merge the commit requests so can't push data to live tool - can approve them but can't do the next step to merge, so commits just sitting in limbo. 
Previoulsy Mango have pushed them through but need to be self-sufficient in team. 
Query if could it be related to permission (is Admin permission level needed - does Admin permission still force through commits without checking?) . Do we need someone separate to Max & Alex to push throughthe merges?
If permissions related, this is something we should document this within the wiki?

**Comment by dougmet** [comment]
I've made you admin, @AnnCorp

**Comment by AnnCorp** [comment]
Thanks @dougmet - we'll test pushing some stuff through and consider as you suggested if have separate admin usernames for people who need to enter and approve data.

**Comment by AnnCorp** [comment]
@Dougmet We need to ensure something in the wiki re permissions and what's needed to do what.

**Comment by AnnCorp** [comment]
Having Admin access sorted the issue - I could fully push through the commits. Team agreed need second admin login within team. @dougmet could we talk through this on Tues pls

**Comment by dougmet** [comment]
Moving wiki task to a new issue

**Comment by dougmet** [comment]
Have updated the [wiki](https://github.com/datasciencecampus/sdg-indicators/wiki/Permissions-for-Adding-Data)

**Comment by AnnCorp** [comment]
Wiki entry looks good - thanks.
