### ISSUE TITLE
Compliance with GDS browser guidelines

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#307]
Need to provide summary documentation/evidence of how the SDGs tool complies with GDS cross browser and responsive guidelines
https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices 
Raised by our Digitial Publishing team.

- [x] Run browserstack
- [x] IE 8/9 data #615 

Need estimate how long this will take?

**Comment by AnnCorp** [comment]
Think could close #123 and just leave this issue #307 (sorry, didn't see 123...)

**Comment by shaneporter** [comment]
There are undoubtedly some compliance issues with the current website. I have worked with progressive enhancement in the past, but I think it may take a relatively large amount of work to achieve compliance.

Is there a team that can validate the compliance of the website? I'm looking at the 'browsers to test in' and we don't have access to all of those as far as I know. If you have access to a specialised team, who can raise and test issues, it would be easier for me estimate an overall amount of time - the subject is quite broad, and I wonder whether I will miss things from the estimate.

**Comment by AnnCorp** [comment]
I'm exploring this with an ONSteam that undertakes some other service assessments.

**Comment by AnnCorp** [comment]
@shaneporter could you get access to 'Browser Stack' https://www.browserstack.com/ (free trial?). Have just been told this is something that has been used by ONS developers.

**Comment by shaneporter** [comment]
Yeah, I've used that in the past - the free trial only gives me 30 minutes though.

**Comment by AnnCorp** [comment]
Well you do work pretty fast! Seriously, is it something that you could obtain in Mango?

**Comment by shaneporter** [comment]
Thoughts @dougmet?

**Comment by AnnCorp** [comment]
@dougmet @shaneporter do you think would be more manageable split this issue to separate the browser stuff from progressive enhancements or yu happy to keep as one big one?

**Comment by shaneporter** [comment]
Things need to be split. Much easier to manage and track.

**Comment by shaneporter** [comment]
I've been thinking about this, and generally speaking, there are a few (big) issues that I can think of when JavaScript is not available.

- (Indicator) search. The website is client side only - no server, so we can't fall back on an html `form` POSTing data to a server, which responds. No JavaScript = No search... which means...
- The menu for smaller screen devices (viewport width of 768px or less) will not function without JavaScript. Some form of progressive enhancement needs to be adopted in this scenario.
- Indicator page tabs - these do not work with JavaScript. This isn't acceptable because the visually hidden text is crucial for the page.
- Graphs and selections do not work - shouldn't be a surprise, but there needs to be some work done so that the page looks good.

**Comment by AnnCorp** [comment]
I'm meeting with one of the senior managers from Digital publishing on Monday so aiming to gauge how far we have to comply with these guidelines at this stage and what if anything could be looked at further in the development. Will report back...

**Comment by AnnCorp** [comment]
Have split out the content re progressive enhancement into a new issue.
Discussed compliance with browser guidelines with Andy Dudfield, head of Digitial Publishing service. 
Re meeting these standards, Andy would be happy if out tool passes favourably through a test using Browser Stack. If hit any issues then need to document them and could then discuss further with Andy.
@dougmet what were your thoughts on getting use of Browser Stack please?

**Comment by dougmet** [comment]
We can definitely use Browser Stack

**Comment by AnnCorp** [comment]
Discussed with head of Publishing (Andy). As per the GDS guidelines, need to be compliant with commonly used browsers (see GDS link at top) . Priority is that that are no poss errors in interpretation of data due to any issues around browsers etc. 
The quick automated test from Digital Accessibility Centre (DAC) raises some compatibility issues, though mostly with older browser versions.
We have previously had an isue where y-axis displayed differently between IE and Chrome

**Comment by dougmet** [comment]
I have a browser stack account. Extremely quick visual report:

Windows XP
IE 8-9 the chart doesn't work. IE 10 it does. IE 11 looks good.
On IE 8 the metadata tabs are visible but don't concertina. This doesn't greatly impact usability.
IE 6 is very bad, but we are not supporting this.

Mac OS
Safari 7 (old) looked good.
Firefox 5.4 looked good

We're not going to fix the charts in IE 8/9 but it only needs to be "functional" according to guidelines. So  if there were

**Comment by dougmet** [comment]
See #615 for IE 8 / 9 thoughts

**Comment by dougmet** [comment]
IE 9 is now functional thanks to the poylfill that @shaneporter implemented. IE 8 is as functional as it can be given that it doesn't support canvas elements. We now have good browser coverage.

**Comment by AnnCorp** [comment]
@dougmet @shaneporter Sounds good re IE9!
Re IE 8 please what actually displays when the charts don't work - could you chuck a screen shot in here please so I can show Andy.

**Comment by dougmet** [comment]
So on IE 8 it looks like this (apologies for resolution) and ou can click the metadata/source tabs

![bs_win7_ie_8 0 1](https://user-images.githubusercontent.com/5878305/32235511-92fd2d02-be57-11e7-9189-2fdc3abce4ef.jpg)

**Comment by dougmet** [comment]
The strangest thing with IE 8 is the front page, which looks like the mobile site.

![bs_win7_ie_8 0](https://user-images.githubusercontent.com/5878305/32235593-c96d05f6-be57-11e7-9fc9-c85a845d6dd6.jpg)

**Comment by shaneporter** [comment]
IE8 doesn't natively support media queries, so no surprise there. There are solutions out there though, which I've used in the past for this.
