### ISSUE TITLE
Compliance with digital accessibility best practice [need estimate]

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#308]
Need to document compliance with best practice for digital accessibility https://www.gov.uk/service-manual/helping-people-to-use-your-service/making-your-service-accessible-an-introduction
Requested by Digital Publishing team.
[for info will also arrange testing through Digital Accessibility Centre] 
Need resource estimate for this pls.

**Comment by shaneporter** [comment]
I wouldn't describe myself as an 'accessibility specialist', so it's difficult for me to estimate times to change things if I don't have a comprehensive list of items to resolve.

What's the feasibility of getting the website tested prior to resolving the issues?

**Comment by shaneporter** [comment]
Citing the link content (emphasis mine):

> ### Testing your service yourself
> 
> You can find some accessibility issues by running an automated tool against your site and by doing regular manual checks.
> 
> You can use an automated tool to regularly test your service’s accessibility while you build it and after you launch, for example:
> 
> WAVE (Web Accessibility Evaluation Tool)
> Tenon
> HTML_Sniffer
> 
> You must not solely rely on using automated tools to check accessibility - **they can only find 20% to 30% of issues**.

I have looked at a couple of the pages with WAVE, Tenon and HTML_Sniffer, and it found some issues - I estimate fixing those would take 1-2 days, but further fixes for issues that may be found by other means will take longer (and I don't know the scope of those issues yet.)

**Comment by AnnCorp** [comment]
I've spoke to @nirenbasu this morning about the Digital Accessibility Centre (DAC) doing some testing for us, initially using some form of automated testing - Niren will send me more info.
Our Digital Publishing team were in the first instance looking for information on what we had done to meet best practice - the tests you're running could contribute to this. Could you add av  brief note on what kind of issues you've found please?

**Comment by shaneporter** [comment]
I'll do some automated testing using WAVE and Tenon and fix the issues; will list them here in due course.

**Comment by shaneporter** [comment]
The issues I've found are:

- Elements must have sufficient color contrast
- Form elements must have labels
- Headings must not be empty
- Frames must have title element
- HTML elements must have a lang attribute
- Redundant links
- Long alternate text (for images)
- Missing first level heading

In many cases, but not all, these issues are found in the same shared elements that are shared across pages.

**Comment by AnnCorp** [comment]
Cheers. Pls let us know if you need any input from SDG team on any of these (text for images - does this include describing charts?) or are they all things you can sort?

**Comment by nirenbasu** [comment]
Hi Ann,
Would be great if someone could complete the ages - Mean, SD - Sure there will be something else but that is all I can think of at the moment.
Thanks
Niren

**Comment by nirenbasu** [comment]
Hi Ann,
Here is the first draft of the report. If you could have a look, any feedback will be greatly appreciated. Note task completion rates were not compiled as this would mean looking through the video.
Thanks
Niren

**Comment by dougmet** [comment]
Removed some email text and a comment that looked like it wasn't meant to go here.

**Comment by dougmet** [comment]
Marking as complete. Any problems from manual testing can get their own ticket.

**Comment by AnnCorp** [comment]
Doug confirmed passed all the automated tests - no known issues now. Ready to proceed to testing with Digital Accessibility Centre.

**Comment by AnnCorp** [comment]
Waiting on details from  ONS user research contact s for DAC.
