### ISSUE TITLE
Remove ONS branded persistent footer [estimate 1 hour]

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#309]
Requested by Digital Publishing team to remove the entire ONS style persistent foot from all pages.
Note will need to add some form of 'Contact us' element somewhere (perhaps in a renamed 'News and Events' - > 'About')
Need resource estimate for this pls.

**Comment by AnnCorp** [comment]
We need to get rid of everything in the footer including the OGL stuff please. Think we just get rid of the whole black footer strip?

**Comment by shaneporter** [comment]
OK - fair enough. Will do that now.

**Comment by shaneporter** [comment]
I've removed the footer in PR #321.

However, I believe it is detrimental not to have a footer on the website. The design is somewhat spoiled - the footer gave the site some form of symmetry, and there is a place for some links down there.
