### ISSUE TITLE
Guidance on how we set up the UK version of the US SDGs tool in GitHub

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#31]
Adding v.02 of guidance to repository - incorporates Ann Corp's early draft and Doug Ashton's technical additions.
[How the UK have set up their copy of the US SDGs tool v0_2.pdf](https://github.com/datasciencecampus/sdg-indicators/files/861443/How.the.UK.have.set.up.their.copy.of.the.US.SDGs.tool.v0_2.pdf)

**Comment by nathaneastwood** [comment]
More to do, but putting on hold for now.

**Comment by dougmet** [comment]
I'll at least copy the contents of the pdf into the wiki. When we get back to it this ticket could cover:

- [ ] Documentation for developers wanting to fork the repo
- [ ] Scripts to run that will reset the data
- [ ] Scripts to step through changing the config files, swapping flags etc.

**Comment by dougmet** [comment]
Make sure to mention that you don't need to give prose.io access to private repositories.

**Comment by nathaneastwood** [comment]
[This is now included in the Wiki](https://github.com/datasciencecampus/sdg-indicators/wiki/How-to-recreate-this-website-for-your-country)
