### ISSUE TITLE
Review load limitations and conduct testing [need estimate]?

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#310]
Consider any load limitations for github, consider what level of use SDG tool going to have and test it, under load, appropriately. Requested by Digital Publishing.
Some initial work done to review github limitations earlier in the project - need to pick this up again. See file GitHubLimits.docx in trello card
https://trello.com/c/4lPhDc8X/37-explore-risks-constraints-with-github-pages-and-document-mitigation-contingency-plans
The doc notes notes the github soft bandwidth limit of 100GB per month - is there a way we can translate this into actual usage, based on page/file sizes eg how much bandwidth used if a person enters at home page then views and downloads files for three indicators?

Task:

- [ ] What is the average bandwidth per visitor?

**Comment by dougmet** [comment]
I'm still thinking about cloudflare for this but we might need to discuss domain names (`sdg-something.org` offline first)

**Comment by AnnCorp** [comment]
@dougmet  If after analysing the risk we need to do something then would have to get approval for this, so need to move quickly on fully understand what happens if hit the soft bandwidth limit (contact GitHub support?) and how likely this is (understanding how the bandwidth gets used up).  
Is the limit per calendar month? If so, then presumably publishing later in the month means more likely to hit it?

**Comment by AnnCorp** [comment]
Suggestion from team that we find out how US mitigated for this, if they did.

**Comment by dougmet** [comment]
Their `gsa.github.io/sdg-indicators` Site is the staging site and the public site is on a different domain. I don't know if that was cloud or local.

**Comment by dougmet** [comment]
I've done an analysis of page loads for a typical visit. Shane thinks we can get it down a bit but we're currently on ~ 450kB per visit (load home page and a few clicks around). Almost all of this is from images. Translating this into bandwidth constraints (100GB) we'd be looking at:

`~220,000` unique users per month.

The reason for the unique is that if you visit the site multiple times your browser will have cached the images.

If we can reduce image size, or even host them elsewhere (just the images) then we may be able to drop this further.

**Comment by AnnCorp** [comment]
That's really helpful, thanks, and great if we could reduce image size further. Once we understand more about the impact of hitting the soft bandwidth and how monitor/check how close we are to it then I'll discuss further with our Digital Publishing team.

**Comment by dougmet** [comment]
I have contacted GH support. Will see if they reply.

**Comment by AnnCorp** [comment]
Discussed with Andy Dudfield, head of Digital Publishing Service. Talked through what we've found so far and the plans to try and further reduce impact of images. Current thoughts are that should be able to proceed without conducting load testing -  subject to getting better understanding from github re what happens when hit the limits and documenting our findings so can share them with Andy.

**Comment by AnnCorp** [comment]
Meeting scheduled with Andy for 9 Oct.
Need updated idea of footprint ie any further reductions with reduced image sizes (any more work to do with this)

**Comment by AnnCorp** [comment]
Discussed with Andy Dudfield ahead of tool soft launch 9 Nov and he was happy with the low risk of hitting limits. Doug monitored through Google Analytics after launch and we were long way from limits.
