### ISSUE TITLE
'About' page instead of 'News & Events' [1 hour]

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#314]
SDG team want to introduce some form of 'About' page for high-level info about the tool and project, links to wiki info etc. Suggest rename News & Events paage as not planning to develop that pre Oct publication. Likely add contact details in here too.
SDG team will provide content.
Need to understand what options we have for editing this text ourselves going forward.

Tasks:

- [ ] Swap news for about page
- [ ] Add wiki entry for editing

**Comment by dougmet** [comment]
At worst it will be a page that you edit directly from GitHub interface (this isn't too bad actually, there's a nice text editor built in). At best we can add it to the prose configuration and you can edit it there, with full pull request functionality etc.

**Comment by shaneporter** [comment]
We can easily 'remove' the 'News and Events pages' from the jekyll build by setting a config option.

Creating a new page, especially if content is provided, will take less than an hour.

**Comment by dougmet** [comment]
Hi @AnnCorp , the code for this is done. I just need some content and then I'll merge it in.

**Comment by AnnCorp** [comment]
SDG team yet to supply content - to follow soon!

**Comment by AnnCorp** [comment]
@dougmet will email you the initial text - sorry for delay.
