### ISSUE TITLE
Add overall Reporting Status [estimate needed]

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#315]
Please add an overall Reporting Status above the goal-specific bars, showing the totals for all indicators. US already have this in https://gsa.github.io/sdg-indicators/status/ so hoping can just reuse code?

**Comment by shaneporter** [comment]
We also just have percentages for each of the status types, whereas they have the count and the percentage - I think that's useful too. Adding _that_ part should take less than an hour.

Will update estimate for 'overall' reporting status after investigation.
