### ISSUE TITLE
Include indicator reporting status on goals page

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#320]
SDG team would like a way of showing users on the goals page which indicators have data within the tool and which don't, so they don't have a potentially pointless journey into indicator pages where there is no data eg on https://datasciencecampus.github.io/sdg-indicators/good-health-and-well-being/ would want to idintify which 4 indicators have data.
Team have suggested including reporting status - poss just showing status for those that are actually reported on line ie in the tool.
Other suggestions have been to dim/grey text if where data not reported online - pls could we discuss options on this element.

**Comment by shaneporter** [comment]
We use a colour for a status on the reporting status page, so for consistency, I'd suggest we use this approach on the goal page too. This is more obvious than a shade of grey.

Also, the Americans have a (summary page, per goal)[https://gsa.github.io/sdg-indicators/no-poverty/], but if this info is on the goal page anyway, perhaps we don't need to duplicate it.

**Comment by shaneporter** [comment]
In fact, as we've seen, the reporting status is important for users wishing to dive down into the indicators page, so it begs the question, why is this information not integrated into the existing goals and indicator pages and removed from the separate 'Reporting Status' area of the site?

**Comment by dougmet** [comment]
You mean, have the goal level reporting status at the top of each goal page? I like that.

I like having it all in one place as well though. Don't see the harm in leaving it there.

**Comment by AnnCorp** [comment]
Def think useful having it all together too but yes, aiming to integrate some of the reporting status stuff into our goal page.  Debated whether have all reporting status appearing next to indicator title (as in US page) or given the distinction we're wanting to make is just whether or not there's data there to dip into, is the important thing to distinguish just whether or not there's data that ie which are reported online.
Could we just add reporting status in first instance (not worry about the greying out) and see how clear it is?

**Comment by AnnCorp** [comment]
Sending to SDG team for feedback.

**Comment by AnnCorp** [comment]
Discussed with Claudia Wells. Happy clear enought with just including reporting status so def dropping idea re greying out. Two thoughts on current layout:
1. makes page longer (mindful will get longer again in future when add Targets)
2. splits number from indicator text and is quite dominant
Thoughts please on if instead of having coloured bar full width of column, just have as long as the text eg as in US version https://gsa.github.io/sdg-indicators/good-health-and-well-being/.
Could right-align this and either position on separate line as-is or try on same line as indicator number - latter would help with (1) above
US do white text on coloured box - if did this would make the status 'badge' seem more distinct from the indicator number and text which are black which helps with (2)?

**Comment by shaneporter** [comment]
Yes, I take your points - I can move it up onto the same line as the indicator number - there's enough space there.

However, the US statuses do not have sufficient color contrast, and fail a check with the aXe Chrome browser plugin. Ours do not fail :smile:.

**Comment by AnnCorp** [comment]
Amendments completed - happy to close.
