### ISSUE TITLE
Reporting status page doesn't function without JavaScript enabled

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#326]
This is related to #307, but worth raising because it's an entire page that is affected by the 'progressive enhancement' guidelines.

Basically, the current implementation makes a separate request (using JavaScript) to get 'indicator' information and render the figures and the relative widths for the 'status bars'.

Without JavaScript, it looks like this:

![image](https://user-images.githubusercontent.com/2493614/30700780-7cc58732-9ee0-11e7-9e46-9878a9f6ecc2.png)

Clearly this isn't acceptable because the pertinent information isn't available to a user with just HTML.

This information needs to be generated by Jekyll so that it is statically included into the page and available to all browsers.

**Comment by dougmet** [comment]
Isn't this the same for CMS based web pages? Just wondering if we're setting the bar a little high?

**Comment by shaneporter** [comment]
What's missing is just text, and this text is key to the purpose of the page, so I'd say that in this case, the text should be generated statically.

**Comment by dougmet** [comment]
Right oh
