### ISSUE TITLE
GDS progressive enhancement compliance

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#337]
Need to provide summary documentation/evidence of how the SDGs tool meets GDS standards on progressive enhancement
https://www.gov.uk/service-manual/technology/using-progressive-enhancement
Raised by our Digitial Publishing team - Andy Dudfield.
[Splitting this work out from issue 307 which will now just cover the browser aspects]

- [x] Headline data visibility: #388
- [x] Clear selections: #389
- [x] Search box: #390
- [x] Metadata: #391

**Comment by AnnCorp** [comment]
From Shane Porter
I've been thinking about this, and generally speaking, there are a few (big) issues that I can think of when JavaScript is not available.

- (Indicator) search. The website is client side only - no server-side processing, so we can't fall back on an html form POSTing data to a server, which responds. No JavaScript = No search... which means...
- The menu for smaller screen devices (viewport width of 768px or less) will not function without JavaScript. Some form of progressive enhancement needs to be adopted in this scenario.
- Indicator page tabs - these do not work with JavaScript. This isn't acceptable because the visually hidden text is crucial for the page.
- Graphs and selections do not work - shouldn't be a surprise, but there needs to be some work done so that the page looks good.

**Comment by AnnCorp** [comment]
@shaneporter Discussed with Andy Dudfield, who heads up the Digital Publishing service area. Suggested be best for you guys to discuss the tehnicalities in more detail -w ill send through contact details via email and see if can get a meeting set up.

**Comment by AnnCorp** [comment]
Meeting set up with Andy Dudfield 9 Oct.

**Comment by dougmet** [comment]
After discussion with Andy we are going to have the headline indicator data (one value per year) visible without JS. Also need to hide the "Clear Selections" button and search box.

If easy (only if easy!) if the metadata could also be visible that'd be great.

**Comment by shaneporter** [comment]
I've split these issues out:

Headline data visibility: #388 
Clear selections: #389 
Search box: #390 
Metadata: #391

**Comment by dougmet** [comment]
With the closing of #391 this is working really well without JS now.
