### ISSUE TITLE
Add analytics to site

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#341]
So that we can monitor usage. Mostly to make sure we don't overshoot GitHub's limits.

**Comment by shaneporter** [comment]
We already have some Google Analytics code in `footer.html`, just need to generate a new tracking ID.

**Comment by dougmet** [comment]
This will be a team effort between @gingerbenw and myself. Ben's setting up an analytics project for this and I'll add the tracking ID into the Travis build so that it only gets deployed in production. Assigning to Ben for now and once you've sent me (not here) the tracking ID assign it back to me

**Comment by dougmet** [comment]
This is live on prod. Contact me for details.
