### ISSUE TITLE
 metadata is not displaying in prose

### ISSUE THREAD

**Issue by Laura-grajewski** [datasciencecampus/sdg-indicators#343]
The metadata is not displaying in prose, even where metadata definitely exists.

**Comment by AnnCorp** [comment]
@dougmet please could you make this the highest priority ticket over any other development stuff. Max and Laura have tested and even when there is metadata, which correctly displays on metadata tab, when try to edit it, all of the metadata fields are showing blank and not the data.  
High impact as we can't currently edit metadata.

**Comment by dougmet** [comment]
When did this start? Trying to link this to something I've changed.

**Comment by dougmet** [comment]
OK, I've narrowed it down. Somehow I added duplicated into the metadata when I fixed the `graph_type` issue. I'll try a bulk fix to my previous bulk edit.

**Comment by dougmet** [comment]
I believe this is now fixed. @Laura-grajewski can you confirm?

**Comment by dougmet** [comment]
Frustratingly there's no option on `yaml.load_all` to fall over with duplicate keys (the R version does but I'm not bringing another language in now!). Will look to add another check in the build. However, data coming from prose should be immune from this as it's a form that won't let you make duplicate keys.

**Comment by AnnCorp** [comment]
@MaxEngledew could you and Laura both test please?

**Comment by MaxEngledew** [comment]
@AnnCorp seems to be fine now. Also @Laura-grajewski has successfully submitted a pull request #345 - so that seems to work too - just decline that one please!
