### ISSUE TITLE
Bulk upload of additional info where not yet reported online

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#350]
Need to add info to additional info box where exploring data or stats in progress - will help clearly communicate to users what the indicator status is when they see a page with no graph or table and page just starts with Metadata.
Have some draft text from Claudia Wells - will add here...
Need to do this now before start actively editing the additional info.

**Comment by AnnCorp** [comment]
Exploring data sources
We are still looking for a suitable data source for this indicator. Please contact use if you think you can help by emailing SustainableDevelopment@ons.gov.uk
In the future we plan to split this category so we can show you which indicators represent data gaps are currently in development and which are still left to look at.

Statistics in progress
We have found a suitable source of data for this indicator or relevant proxy at national level. We are currently quality assuring the data and preparing it for publication.

**Comment by AnnCorp** [comment]
@dougmet We need to change the wording for the 'Exploring data sources' one  please - my fault, sorry. Just need the following bit, not the second sentence:
We are still looking for a suitable data source for this indicator. Please contact use if you think you can help by emailing SustainableDevelopment@ons.gov.uk

**Comment by dougmet** [comment]
OK, that was quite simple as it's just a removal.

**Comment by AnnCorp** [comment]
Looks good thanks - ok to close.
