### ISSUE TITLE
Hierachical Filter

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#352]
Where there are parent-child relationships between disaggregation columns. The child should not be available to choose unless the parent has been selected.

Remaining tasks:

- [x] Group columns in parent-child order #998 
- [x] Visual hints of child categories #1001

**Comment by dougmet** [comment]
For auto-detection of parent child we used the following rule, for imaginary column's `A` and `B`

| Year | A | B | Value
|:-----|:---|:---|-----:|
| 2015 | A1 | B1 | 1.001 |
| 2015 | A1 | B2 | 1.001 |
| 2015 | A2 | B1 | 1.001 |
| 2015 | A2 | B2 | 1.001 |

1. If `B` is never present without `A` then `B` is a child of `A`
2. If `A` is never present without `B` then `A` is a child of `B`
3. If both of the above are true then whichever column is on the left. In this case that means `A -> B`

**Comment by dougmet** [comment]
@shaneporter is the above easy to implement in JS or would you like more examples?

**Comment by dougmet** [comment]
For a minimum version I think we need to give a visual hint that parents have children.

**Comment by dougmet** [comment]
@gingerbenw can do some of this with CSS. The other issue is the ordering of fields. Children need to sit immediately under their parents. One suggestion is that we reorder the columns build-side. So I would rewrite each indicator reordering the columns so that parent-child-grandchild ordering is correct.

**Comment by shaneporter** [comment]
I was thinking about the ordering, and could do this fairly easily in the JavaScript.

How would CSS alone resolve the 'parents have children' visual hint? When does this need to be done for?

**Comment by dougmet** [comment]
Good news re ordering. We played with CSS subtlety indenting child select boxes instead of hiding them. Would love something more direct though. 

The need for the hints is because when the page loads there's no way to know that children exist until you happen to choose a parent.

**Comment by dougmet** [comment]
Done! Great job Shane.

**Comment by shaneporter** [comment]
Thanks for the edges @dougmet :smile:
