### ISSUE TITLE
Need bar chart option fully working

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#353]
In metadata already exists to select bar or line chart. Doug advised may need more work to ensure this is fully working.
Instances where may want bar chart are where there is only 1 time period or if not continuous time series.

**Comment by MaxEngledewAdmin** [comment]
16.2.3

**Comment by MaxEngledewAdmin** [comment]
6.5.1, 6.5.2

**Comment by AnnCorp** [comment]
@MaxEngledewAdmin could you have a test of this one please with indiators where you'd expect to use bar char. In 6.5.1 seems quite a chunky bar.
@gingerbenw I'll just bung it in review until Max has tested.

**Comment by MaxEngledewAdmin** [comment]
To sum up from discussion on #564 - There should be some indication that the value is 0 as opposed to there being no value.

**Comment by MaxEngledewAdmin** [comment]
For example [6.5.2](https://datasciencecampus.github.io/sdg-indicators/6-5-2/) (%) units type

**Comment by gingerbenw** [comment]
ahh! brilliant, thanks max! I was struggling to find an example :)

**Comment by gingerbenw** [comment]
Rendering values of 0 looks to be a lot of work where the feature has been removed from ChartJS.

The Legend does show that the selection is included, so we agree that this minor fix can be shelved for now. Overall issue can now be closed.
