### ISSUE TITLE
Graph is squashed

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#354]
This is not the most extreme example I've seen but the graph is looking more and more squashed as extra footnotes and select boxes are added

![image](https://user-images.githubusercontent.com/5878305/31228581-e9a68c66-a9d5-11e7-8a9d-6cfec108e1c3.png)

**Comment by dougmet** [comment]
Here's how it looks on iOS for me as well:
![squashgraph](https://user-images.githubusercontent.com/5878305/31289610-3a8d6aaa-aac1-11e7-8a99-4c1ba612e06a.jpg)

**Comment by shaneporter** [comment]
hi @dougmet - my graphs aren't squashed, and I've tried resizing the browser to see things at different viewport widths, but still no squashing.

What browser/version are you using? Thanks.

**Comment by dougmet** [comment]
The iOS one is Safari on iOS 11.0.2.  The Chrome one I seem unable to reproduce today. But it was Chrome  61.0.3163.100

**Comment by AnnCorp** [comment]
Just to say I'm not getting the squashed graphs today either and was getting lots of problems with it.  I'm on Chrome 55.0.2883.75 m

**Comment by shaneporter** [comment]
Fixed the issue it seems (the graph's height was based on the screen height, and for devices with smaller screens, they graphs would typically be squashed).
