### ISSUE TITLE
Progressive Enhancement - Headline Indicator Data

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#388]
Headline Data should be visible without JS enabled.

**Comment by shaneporter** [comment]
Is it possible to generate the 'headline data' in another file, as part of the build @dougmet?

Doesn't seem a way to loop through the existing CSV with Jekyll and check for rows with only the 'year' and the 'value' fields set.

**Comment by dougmet** [comment]
As it stands I can't do that without moving the build completely over to Travis. Which we can do (I've solved most of the problems around this) but is quite big change. I understand the issue, will have a think about it.

**Comment by shaneporter** [comment]
Had another look, and there's doesn't seem to be anything that's robust enough. Another suggestion is to add another column, `is_headline`, set to `true` for those 'headline' rows, but it's probably not ideal since it'll involve a huge data update and ongoing maintenance and other code changes.

**Comment by dougmet** [comment]
OK, I think I'd rather move the build to Travis than do that. Leave with me.

**Comment by dougmet** [comment]
Build side is done in #541 but will need to be plumbed into the cibuild.sh file once we move to develop.

**Comment by dougmet** [comment]
This links up with considerations for browser support. See #615

**Comment by dougmet** [comment]
As discussed some adaptation of this may help:

```
{% assign mydata=site.data.foo %}

<table>
    <caption>Table caption</caption>
    <thead>
    {% for column in mydata[0] %}
        <th>{{ column[0] }}</th>
    {% endfor %}
    </thead>
    <tbody>
    {% for row in mydata %}
        <tr>
        {% for cell in row %}
            <td>{{ cell[1] }}</td>
        {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
```

**Comment by dougmet** [comment]
This is how it currently looks without JS
![image](https://user-images.githubusercontent.com/5878305/32057461-389a5872-ba5f-11e7-8fbb-33fec872f701.png)

The metadata changes will likely have to stack up the data and metadata
