### ISSUE TITLE
Progressive Enhancement - Display Metadata

### ISSUE THREAD

**Issue by shaneporter** [datasciencecampus/sdg-indicators#391]
Metadata is currently hidden in a tab's content, switchable only if JS is enabled.

Metadata should be visible to all visitors, irrespective of JS.

**Comment by dougmet** [comment]
If you set all of the tabs to "active" and all of the collapsibles to "expanded" then you see everything. When the JS appears it could go through and deactivate and collapse the right things. This is how it would look with JS switched off

![image](https://user-images.githubusercontent.com/5878305/32062906-c499417c-ba6d-11e7-9160-5bfe31f4099a.png)

**Comment by shaneporter** [comment]
Thanks for the pointers @dougmet
