### ISSUE TITLE
Graph title for 5-4-1

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#461]
I think the graph title might be wrong. It says women in the title but that's just one of the disaggregations. 

https://datasciencecampus.github.io/sdg-indicators/5-4-1/

**Comment by MaxEngledewAdmin** [comment]
@dougmet thanks! We'll pick this up in indicator QA - Prioritizing those which are on the tool already so this should be fixed soon.

**Comment by dougmet** [comment]
If the words `fixes #461` are in the commit message then this ticket will automatically close when he update goes in.

**Comment by AnnCorp** [comment]
@MaxEngledew am closing this ticket as you'll be sorting this within your team
