### ISSUE TITLE
Text for headline download

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#487]
It's not clear enough what the download buttons do. 

![image](https://user-images.githubusercontent.com/5878305/31615595-f331d66e-b281-11e7-91bc-0632a2ed634a.png)

The top button here downloads the source (this is correct, its the raw data). The bottom button downloads the headline data only. The reason it's not too clear is that the data used to update dynamically. Recommend we change this to "Download Headline Data"

Will assign to Ben once I've added him to the team.

**Comment by AnnCorp** [comment]
Max and I suggest as well as having more explicit labels, then could help to position the buttons closer to each other.

**Comment by dougmet** [comment]
Duplicate of #489

**Comment by gingerbenw** [comment]
There are also some issues with button colours, after clicking a button to download a CSV, it changes to blue. Is this intended, or would we like to create some more rules to ensure the buttons don't change colour?

**Comment by AnnCorp** [comment]
I don't think it should change colour like this - while we're not branding as ONS, reckon should be consistent with what we do for something like this on main ONS website  and we don't change colour. Example here https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/consumerpriceinflation/september2017
Sometime in future, likely want to add an option to download an image too, so may wish to factor that into layout.

**Comment by gingerbenw** [comment]
![screen shot 2017-10-20 at 15 42 47](https://user-images.githubusercontent.com/24570483/31826658-8b3fb754-b5ad-11e7-9e20-8ed8d8f4f46d.png)

Buttons moved and relabelled, they no longer change colour and the CSV is now forced as a download instead of opening in another window in certain browsers

**Comment by dougmet** [comment]
Button has vanished! When it's back, let's try a few configurations and paste results here.

**Comment by gingerbenw** [comment]
Raised a bug ticket #857 - Have posted a fix there.

**Comment by AnnCorp** [comment]
All sorted.
