### ISSUE TITLE
Should we build on Travis?

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#50]
master branch would become main branch. Travis would run jekyll build and push successful builds back to gh-pages.

Advantages:
- Allows to use more ruby libraries
- Allows more advanced data pre-processing with Ruby/Python/R whatever
- Pre-processing could be valuable for the front page "dashboard"

Disadvantages:
- Slightly harder for people wishing to copy the site (still free though)
- Will take an hour or so to set up.
- PAT is specific to one person who must retain access

**Comment by dougmet** [comment]
This would also free us from the rigidity of the liquid template language. GitHub pages standard is to have all of the safe flags on and generally lock down. Travis does not worry about such things so building there would allow us to write more powerful code.

**Comment by dougmet** [comment]
This would let us use Jekyll plugins to do various interesting things.

Momentum is swinging towards this. I will aim to make a prototype in my personal fork.

**Comment by nathaneastwood** [comment]
Travis allows you to build, test and deploy to various different services, including [GitHub Pages](https://docs.travis-ci.com/user/deployment/pages/). I have used this successfully on the [coding-standards](https://github.com/datasciencecampus/coding-standards/blob/master/.travis.yml) repo.

**Comment by dougmet** [comment]
This is actually happening now (forgot to tag the ticket) in a limited sense. The build on travis (not using any fancy modules, still gh-pages compliant), from the *master* branch, pushes the `_site` directory via ssh to another GitHub repo. Keys are encrypted in travis.

**Comment by dougmet** [comment]
So to answer the issue with PAT tokens. I went down and SSH-key route because these keys are unique to a project *not* a user. This mitigates the issue of someone leaving and we don't have a valid PAT.

**Comment by dougmet** [comment]
As of today we've switched to full Travis build.

`develop` branch deploys the `_site` directory back to `gh-pages` in this repository as the staging site
`master` branch deploys to the production repository.
