### ISSUE TITLE
Admin users cannot use Prose

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#54]
For users *without* write access to the main repository prose works really well. You go to edit a file and then you actually edit that file in a fork of the repository. When you hit save a PR is made to the main repo. This is what we want.

If you have write access to the main repository then instead of making a fork prose attempts to commit directly to the main repository. This is not what we want. We want all changes to come in via pull requests and approved with peer reviews.

Short Term Fix: Structure repo permissions to make sure that anyone who adds data through prose has correct permissions. Power users can still make PRs, just not via the prose interface. Also dig about in prose settings to see if there's support for this already.

Long Term Fix: If we fork prose as in #38 then we may be able to change the behaviour to create changes in a new branch rather than attempt to commit directly to the repo.

**Comment by nathaneastwood** [comment]
Having write permissions also creates the additional issue of not being able to use Prose at all since it requires a Travis check. See #166 for more details.

**Comment by dougmet** [comment]
Links to #38

**Comment by dougmet** [comment]
We'll do short term for MVP

**Comment by AnnCorp** [comment]
@dougmet I think if we cover this off in the wiki in a section on permissions then we could close this one. Our workaround is to ensure having data managers with Admin access and Data entry people without but if have to have data entry people with dual role then will consider dual logins, one normal and one with admin.
