### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#555]
@AnnCorp  will confirm the text

**Comment by AnnCorp** [comment]
As a minimum will want:
some form of 'Contact us' which initially could just fire up an email to sustainabledevelopment@ons.gov.uk
FAQ (separate ticket)
Will not contain other stuff in standard ONS footer (eg no OGL stuff)

**Comment by dougmet** [comment]
Hi @gingerbenw if you're able to reinstate the footer with just the contact us part. We'll FAQ when the page exists.

**Comment by dougmet** [comment]
FAQ is now in.

**Comment by dougmet** [comment]
@gingerbenw I've started on this and was about to merge but thought I'd check with you as it's not quite how I remember it looking.

**Comment by AnnCorp** [comment]
@dougmet  @gingerbenw  our Publishing team didn't want the same look and feel for footer as main ONS site (different branding etc) so need to bear that in mind please.

**Comment by dougmet** [comment]
Remove we welcome your feedback

**Comment by gingerbenw** [comment]
Could I also suggest that we add the class `text-right` to the `col-md-6` that contains the 'Frequently Asked Questions' in the Footer, which would result in:

![screen shot 2017-10-31 at 12 58 46](https://user-images.githubusercontent.com/24570483/32224953-49bd2fb4-be3b-11e7-9dea-235be3969a8c.png)
