### ISSUE TITLE
Publications page

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#558]
In identical manner to the about page. Once initial text is received add this to the site.

Document update process in the wiki.

**Comment by AnnCorp** [comment]
@dougmet Here's the intitial text from Jo
[Publication page text.docx](https://github.com/datasciencecampus/sdg-indicators/files/1401111/Publication.page.text.docx)

**Comment by dougmet** [comment]
I've done this, but it looks like I've hit some size limit on the number of pages links:
![image](https://user-images.githubusercontent.com/5878305/31831547-c630ce44-b5bb-11e7-9702-a643fb09b01f.png)

@gingerbenw would it be possible to extend the area? Or will this have a bad effect on mobile sites?

**Comment by dougmet** [comment]
I'm working in branch `e/558`

**Comment by gingerbenw** [comment]
this collapses into a dropdown on mobile, so that wouldn't be a problem. should be a simple fix with a couple of css rules

**Comment by gingerbenw** [comment]
![mobile](https://user-images.githubusercontent.com/24570483/31886506-6edaf970-b7ec-11e7-8a08-9f05a4e0758b.png)
![small](https://user-images.githubusercontent.com/24570483/31886507-6ef2b042-b7ec-11e7-8ac6-d1c9f19d4241.png)
![normal](https://user-images.githubusercontent.com/24570483/31886508-6f099668-b7ec-11e7-8576-fe1a2dcb2fd7.png)

The 'small' version of the page has some strange spacing issues, I guess we'd prefer to have the menu still justified to the top of the div as per the 'normal' screenshot?

**Comment by gingerbenw** [comment]
![screen shot 2017-10-23 at 12 35 56](https://user-images.githubusercontent.com/24570483/31887039-bcff01f8-b7ee-11e7-8645-49abe2321a2a.png)

Fixed :)

**Comment by dougmet** [comment]
This is done. How does it look @AnnCorp ?

**Comment by AnnCorp** [comment]
With Jo Evans for review - awaiting feedback...

**Comment by AnnCorp** [comment]
Jo reviewed and Max and i made minor tweaks ourselves so OK to close.
