### ISSUE TITLE
Emphasise National Level Indicator

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#56]
Part of #19 

When we select groups we always retain the "All" group (which is the line we see by default when a page is loaded). We'd like to bring this line out a bit so that when there are lots of lines on the page the national level (all) indicator is prominent.

- Could be an increased line thickness? 
- Could be that we use alpha on all of the other lines?
- Does Chart.js have a notion of which line goes on top?
- Instead of "All" should it be something else? Space is somewhat of an issue. Maybe in the  hover over text.

**Comment by dougmet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User story: visualisations for disaggregations](https://trello.com/c/JhIe5TpX/50-user-story-visualisations-for-disaggregations)

**Comment by shaneporter** [comment]
Line thickness is a suggested fix for this and is part of PR #63.
