### ISSUE TITLE
Add 'Guidance' page

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#564]
Need a page from which can link to the wiki and then to the further US material.
Ann to provide some initial text then we'll add more once page set up.

**Comment by gingerbenw** [comment]
Guidance page added, header updated.

**Comment by gingerbenw** [comment]
Please see [https://github.com/datasciencecampus/sdg-indicators/tree/e/564]e/564

**Comment by AnnCorp** [comment]
Sorry for the delay in getting this to you @gingerbenw 
[Guidance page initial content.docx](https://github.com/datasciencecampus/sdg-indicators/files/1471202/Guidance.page.initial.content.docx)

**Comment by gingerbenw** [comment]
Added! are we ready to push this for now then?

**Comment by AnnCorp** [comment]
Speedy - thanks Ben. @maxengledew has some test data things to undo and stuff to check on develop (eg bar charts) before we do another push to master. Max could do a push tomorrow or give you the nod to do it (am not in tmrw)

**Comment by MaxEngledewAdmin** [comment]
@gingerbenw I've pushed through #1866. @AnnCorp - Bar charts seem fine apart from not displaying 0 values. 

Will push to master now.

**Comment by gingerbenw** [comment]
Great! thanks @MaxEngledewAdmin :)

Would we like to look into 0 values displaying? or should we raise that as a separate issue for another time?

**Comment by MaxEngledewAdmin** [comment]
@gingerbenw there was initially an issue logged with 0 values not displaying on the line charts (which has since been fixed) so it might be the same fix can be applied to the bar charts. I don't know whether a new issue needs to be raised... but there should be some indication that the value is 0 as opposed to there being no value.
