### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#565]
To link from the About page and from the persistent footer.
Ann to provide initial text.

**Comment by AnnCorp** [comment]
@dougmet Here's some initial text for the FAQ. We discussed potential requirement for being able to link to specific entries too. 
[FAQ draft text.docx](https://github.com/datasciencecampus/sdg-indicators/files/1414495/FAQ.draft.text.docx)
Once this is in, we'll test being able to add more entries ourselves.
[PS have no ONS email today so pls ring on mobile if any urgent queries]

**Comment by dougmet** [comment]
Link in footer #555

**Comment by AnnCorp** [comment]
I think we should actually also link this to the primary menu bar too please - will give more prominence.

**Comment by AnnCorp** [comment]
@dougmet Could we make the various entries collapsible please? Not sure how much effort this is? Planning to add quite a few more entries so would help navigation.

**Comment by gingerbenw** [comment]
```html
<!-- DO NOT EDIT ANYTHING BELOW THIS LINE -->
<script>
	document.addEventListener("DOMContentLoaded", function(){
  	$('#main-content h3').addClass('collapsible');
		$('.collapsible').click(function(){
			$(this).nextUntil('h3').stop(true, true).slideToggle();
		}).nextUntil('h3').hide();
	})
</script>
```

**Comment by dougmet** [comment]
Hi @AnnCorp how does it look now?

We're going to do something about pinning the footer to the bottom but that will be a separate ticket

**Comment by AnnCorp** [comment]
Huge improvement thank you - all good to close.
