### ISSUE TITLE
Accessibility: CSS units

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#566]
Use relative rather than absolute units in CSS property values.
> Absolute units are CM, MM, IN, PC and PT. When used with fonts PX is also considered an absolute unit, because it isn't relative the user's preferred font size. Low-vision users, and a lot of people over 50, increase the browser default font size to make text easier to read. Absolute units ignore this user choice. Relative units like EM and percentages "stretch" according to the screen size and/or user's preferred font size, and work on a large range of devices.

https://datasciencecampus.github.io/assets/css/style.css?v=7626f0c006a9834988aae5c9fffef51c82a26fdb line 105 
https://datasciencecampus.github.io/sdg-indicators/assets/css/default.css?v=20171010134536 line 37  132 150 162 ... 
	Guideline: WCAG 2.0 AA 1.4.4 Section 508 (2017) AA 1.4.4

**Comment by gingerbenw** [comment]
Updated and pull request created

**Comment by AnnCorp** [comment]
Closing as ticket completed last month
