### ISSUE TITLE
Browsers: IE8 / IE9 show headline data

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#615]
We are required for the website to be "functional" for IE 8-10. 10 is fine but 8-9 are not showing the chart or the data. We can live without the chart but the data should show.

I propose that we link this to #388. If it's possible we could use the same strategy. If you're in IE<10 then leave the simple headline table instead. If there's an elegant way to do it then great, if there are a load of `if IE` calls then so be it.

This is the error as reported for IE 9 on Windows 7 in case it's of use.

![bs_win7_ie_9 0](https://user-images.githubusercontent.com/5878305/31843344-5f099a3c-b5ea-11e7-8a71-3c5c4456af8b.jpg)

**Comment by AnnCorp** [comment]
Just discussed with Andy, head of our Digital Publishing Service. 
IE9 widely used in government so prioritise being functional in that, ahead of any issues with IE8.

**Comment by dougmet** [comment]
I think IE8 is out (for the charts) because it doesn't support the `<canvas>` element. IE9 could in principle take the charts. @shaneporter if you get a chance to look after the filtering (I can sort you with browserstack) maybe it'll be clearer for you.

As far as I can tell the only issue with IE9 is that chart not showing.

**Comment by shaneporter** [comment]
I might use this: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/, for that.

**Comment by shaneporter** [comment]
The issue relates to https://github.com/chartjs/Chart.js/issues/4742. 

Despite some suggestions on that thread, it seems that there are some issues with chartjs and IE9.

**Comment by dougmet** [comment]
Good find with the MS tools. Looks like it uses browserstack behind the scenes anyway!

**Comment by shaneporter** [comment]
The Microsoft resources are VMs; there's a BrowserStack ad on there for free Edge testing on their service.

**Comment by dougmet** [comment]
Doug to add a print screen and then resolve

**Comment by dougmet** [comment]
see #307  for screen shots
