### ISSUE TITLE
Pivot the breakdown data table

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#63]
As disaggregations are selected the data tables update. We'd like these data tables these should be pivoted so that groups go in the column headings.

**Comment by dougmet** [comment]
Doug to put an example here

**Comment by dougmet** [comment]
Suppose a user has selected `Grade` and `Planet`. We should get the following outputs:

## All

| Year|   Value|
|----:|-------:|
| 2010| 15.1591|
| 2011| 16.3583|
| 2012| 16.2244|
| 2013| 14.3392|
| 2014| 15.7900|
| 2015| 14.0988|
| 2016| 15.5934|

Should we rename value to all? Well, for now just verify if we can rename it.

## Breakdown by Grade

| Year|       A|       B|
|----:|-------:|-------:|
| 2010| 14.1695| 16.1488|
| 2011| 15.5065| 17.2102|
| 2012| 16.6152| 15.8335|
| 2013| 14.3857| 14.2927|
| 2014| 14.6857| 16.8942|
| 2015| 14.8525| 13.3451|
| 2016| 16.5992| 14.5875|

## Breakdown by Planet

| Year|   Earth| Mercury|   Venus|
|----:|-------:|-------:|-------:|
| 2010| 13.5965| 16.8926| 14.9884|
| 2011| 16.3891| 14.4638| 18.2220|
| 2012| 16.5582| 15.9636| 16.1514|
| 2013| 15.0369| 11.5131| 16.4675|
| 2014| 16.4703| 15.4209| 15.4786|
| 2015| 14.2360| 12.5865| 15.4739|
| 2016| 17.3360| 14.4644| 14.9798|

## Breakdown by Grade and Planet

| Year| A_Earth| A_Mercury| A_Venus| B_Earth| B_Mercury| B_Venus|
|----:|-------:|---------:|-------:|-------:|---------:|-------:|
| 2010| 11.7802|   17.3458| 13.3825| 15.4127|   16.4394| 16.5942|
| 2011| 13.8649|   15.6690| 16.9856| 18.9134|   13.2586| 19.4585|
| 2012| 15.2324|   16.2654| 18.3479| 17.8839|   15.6618| 13.9548|
| 2013| 14.4367|   11.8379| 16.8824| 15.6371|   11.1883| 16.0526|
| 2014| 16.7684|   16.2951| 10.9936| 16.1722|   14.5468| 19.9637|
| 2015| 14.7246|   13.3090| 16.5238| 13.7473|   11.8639| 14.4240|
| 2016| 18.4822|   16.5154| 14.8001| 16.1897|   12.4133| 15.1595|

I've gone for underscore separators; what do you think?

**Comment by shaneporter** [comment]
Thank you - I like 'value as a replacement for 'all'. No strong feelings about using an underscore, but it's easily changed later.
