### ISSUE TITLE
Limit the precision of numbers in plot/table

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#64]
In the hover over we need to limit the rounding.

In the data tables we might want to limit the rounding

**Comment by dougmet** [comment]
Is this a problem with the real world data

**Comment by shaneporter** [comment]
Do we know the answer to your question @dougmet? What are we typically seeing for data-related PRs?

**Comment by shaneporter** [comment]
Thanks - I'll go with that.

**Comment by dougmet** [comment]
Does javascript have the equivalent of this:
```
printf( "%.3g", 3.1415926 );
> 3.14
printf( "%.3g", 3.1415926 / 1000);
> 0.00314
```

**Comment by dougmet** [comment]
Actually that's just significant figures

**Comment by shaneporter** [comment]
I'll most likely have to do a test on the value of the number, and conditionally apply a function:
````javascript
3.1151115.toFixed(2)
````
> 3.12

````javascript
0.00314.toPrecision(2)
````
> 0.0031

**Comment by dougmet** [comment]
So that seems like ideal behaviour. Is that a hassle?

**Comment by shaneporter** [comment]
It's a pleasure, @dougmet :smile:

**Comment by shaneporter** [comment]
In fact, I think this ONS '[Effective rounding](https://style.ons.gov.uk/data-visualisation/tables/number-rounding/)' advice is what I should be doing.

I found it after I found some of my interim solutions, based on a range of numbers, to be insufficient.

**Comment by dougmet** [comment]
The ONS guidelines look great. For this first pass it's probably more effort than we want. In fact I wonder if a general purpose library on datasciencecampus would be useful, @nathaneastwood ? Or maybe there's already something on ONSdigital?

Either way. Let's go with significant figures for now. Let's say 3 unless it looks silly.

**Comment by nathaneastwood** [comment]
Yes there is possibly something on ONSdigital, but otherwise I can create a general purpose repo on datasciencecampus for you if you like.

**Comment by dougmet** [comment]
Not urgent. Just thought it might be reusable so we should avoid just putting it in here.
