### ISSUE TITLE
Chart information

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#66]
Information that sits close to the chart. Ideally using chart.js footers and labels etc. The information are mostly already in the metadata.

Above chart:
- Chart title
- Geographic coverage
- Unit of measurement

Below chart:
- Source organisation(s) (check which field).

**Comment by nathaneastwood** [comment]
Can we close this issue now @dougmet and @shaneporter?

**Comment by shaneporter** [comment]
I'd say so. This work has been done, and any issues can be raised against what I've done.
