### ISSUE TITLE
Disagreggation Interactions

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#68]
If we have data for say Sex *and* Region then we don't see the data rows where *both* are present.

**Comment by dougmet** [comment]
Doug to provide example

**Comment by dougmet** [comment]
This relates to #63 where I showed what the interaction data is. Below is what the data looks like in unpivoted form:

| Year|GradePlanet |   Value|
|----:|:-----------|-------:|
| 2010|A_Mercury   | 17.3458|
| 2010|A_Venus     | 13.3825|
| 2010|A_Earth     | 11.7802|
| 2010|B_Mercury   | 16.4394|
| 2010|B_Venus     | 16.5942|
| 2010|B_Earth     | 15.4127|
| 2011|A_Mercury   | 15.6690|
| 2011|A_Venus     | 16.9856|
| 2011|A_Earth     | 13.8649|
| 2011|B_Mercury   | 13.2586|
| 2011|B_Venus     | 19.4585|
| 2011|B_Earth     | 18.9134|
| 2012|A_Mercury   | 16.2654|
| 2012|A_Venus     | 18.3479|
| 2012|A_Earth     | 15.2324|
| 2012|B_Mercury   | 15.6618|
| 2012|B_Venus     | 13.9548|
| 2012|B_Earth     | 17.8839|
| 2013|A_Mercury   | 11.8379|
| 2013|A_Venus     | 16.8824|
| 2013|A_Earth     | 14.4367|
| 2013|B_Mercury   | 11.1883|
| 2013|B_Venus     | 16.0526|
| 2013|B_Earth     | 15.6371|
| 2014|A_Mercury   | 16.2951|
| 2014|A_Venus     | 10.9936|
| 2014|A_Earth     | 16.7684|
| 2014|B_Mercury   | 14.5468|
| 2014|B_Venus     | 19.9637|
| 2014|B_Earth     | 16.1722|
| 2015|A_Mercury   | 13.3090|
| 2015|A_Venus     | 16.5238|
| 2015|A_Earth     | 14.7246|
| 2015|B_Mercury   | 11.8639|
| 2015|B_Venus     | 14.4240|
| 2015|B_Earth     | 13.7473|
| 2016|A_Mercury   | 16.5154|
| 2016|A_Venus     | 14.8001|
| 2016|A_Earth     | 18.4822|
| 2016|B_Mercury   | 12.4133|
| 2016|B_Venus     | 15.1595|
| 2016|B_Earth     | 16.1897|

**Comment by shaneporter** [comment]
This is handled by PR #63.

**Comment by dougmet** [comment]
Shall we have a separate ticket for the plots? I'm happy with the implementation in the data tables

**Comment by dougmet** [comment]
See #107 for the plot version
