### ISSUE TITLE
Remove dummy data eg 14.1.1

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#685]
Need to remove any dummy data eg 14.1.1 - are there any others we know of?
@MaxEngledewAdmin do you want to do this so you can copy the markdown somewhere re how the table was set up etc (incase want to reuse) - there's links to the markdown guidance from the wiki

**Comment by MaxEngledewAdmin** [comment]
@AnnCorp No problem. 

With regards to the issue title. Is it a problem if there's dummy data on unreported indicators as the data won't display anyway? I think 14.1.1 is the only dummy data that is displaying.

**Comment by dougmet** [comment]
The dummy markdown for posterity:

```markdown
# Test Indicator

The data for this indicator is test data for demonstration purposes only. This notice is part of a free text field where extra information can be added, styled using [Markdown](https://guides.github.com/features/mastering-markdown/), which allows basic things such as **bold**, _italic_, and includes [hyperlinks](https://guides.github.com/features/mastering-markdown/).

Even manual tables can be added:

| Name | Description | Number |
|:-----|:------------|-------:|
|Name1 | Free text   | 17 |
|Name2 | More text  | 0.1 |

Althought the above is not a proper data format.
```

**Comment by MaxEngledewAdmin** [comment]
@dougmet Thanks Doug!

**Comment by dougmet** [comment]
And this is useful https://www.tablesgenerator.com/markdown_tables
