### ISSUE TITLE
8.4.1 Disaggregation not displaying 

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [datasciencecampus/sdg-indicators#688]
[8.4.1](https://datasciencecampus.github.io/sdg-indicators/8-4-1/) Any idea why this specific Unit's disaggregation isn't showing. The data looks fine to me and the other unit of measure is working.
![capture](https://user-images.githubusercontent.com/32291046/31999714-2cb35b18-b98c-11e7-91b1-cd09feb1963a.PNG)

 Even more curiously if you switch the 'UK' line off it switches the Y axis to the other units!

![capture2](https://user-images.githubusercontent.com/32291046/31999939-e95ddf4a-b98c-11e7-9092-d1ab44ac1555.PNG)

**Comment by dougmet** [comment]
Hi @MaxEngledewAdmin, can you check if this is still a bug? I think one of the recent fixes may have fixed this. Looks OK to me.

If it looks OK then we can close this off.

**Comment by MaxEngledewAdmin** [comment]
@dougmet Looks fine to me
