### ISSUE TITLE
Wiki entry re develop/master set up etc

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#711]
Need some documentation in the wiki on the new set up with develop and master etc.
Will be useful for anyone copying our site, but also for anyone jumping in to help out on the project in next few weeks.

**Comment by dougmet** [comment]
I'm filling this in slowly. The release procedures will go here: https://github.com/datasciencecampus/sdg-indicators/wiki/Deploying-with-Travis#deployment-procedure

**Comment by dougmet** [comment]
Last bit remaining is to document setting up Travis for deployment.

**Comment by AnnCorp** [comment]
@dougmet is there still stuff to add to this one?

**Comment by dougmet** [comment]
Yes, I have a few bits to add about deployment keys (back in tomorrow!)

**Comment by dougmet** [comment]
This is done. Regrettably the deployment process is much more complicated now with all of the keys etc. There might be scope to get back to the old setup at some point (we can maybe do headline in Jekyll and edges in js).

I am happy to personally help anyone who is trying to set this up for a country or government organisation.

**Comment by AnnCorp** [comment]
Completed by Doug.
