### ISSUE TITLE
Runaway headline data table

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#856]
See for example 3-2-1

![image](https://user-images.githubusercontent.com/5878305/32217310-837a8984-be1f-11e7-97c7-e68ea0f8117e.png)

**Comment by gingerbenw** [comment]
The button is no longer being added as this test was not passing.

`if(window.Modernizr` && window.Modernizr.blobconstructor)`

Do we actually need this test or can we just add the button regardless? this works just fine if JS is disabled.

**Comment by gingerbenw** [comment]
![screen shot 2017-10-31 at 11 23 51](https://user-images.githubusercontent.com/24570483/32221593-025285e6-be2e-11e7-98fe-150a3de545d2.png)
