### ISSUE TITLE
Scale Issue Indicator 3.2.1 

### ISSUE THREAD

**Issue by MaxEngledew** [datasciencecampus/sdg-indicators#87]
Hi Doug, the scale seems to be running from 2008-15 and then from 2000-07 (tick geography for a clear example of the issue) https://datasciencecampus.github.io/sdg-indicators/3-2-1/. Any idea what has gone wrong here?

**Comment by dougmet** [comment]
That's a new one! So there is data for England & Wales before there is national level data but it's not being properly sorted by year. Any ideas @shaneporter? Happy to dig into the data model if you're busy on other things.

**Comment by dougmet** [comment]
This is fixed. Hit <ctrl>-F5 to see the updated version

**Comment by MaxEngledew** [comment]
Thanks both, there's likely going to be a few where a disaggregation begins before the headline so its great to get this sorted now!

**Comment by dougmet** [comment]
Indeed, really value the testing!

**Comment by dougmet** [comment]
At some point I think we're going to have to talk about the England-and-Wales problem. But let's continue with the small fixes first!
