### ISSUE TITLE
Format Metadata URLs 

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#96]
Some of the URLs are very long and do not render nicely. We will need another metadata field: `source_url_text` that is the text to display and the in the code we have something like:

```
<a href="{{ source_url_i }}">{{ source_url_text_i }}</a>
```

Of course this means we can't just loop through the table. Unless we use this format for *all* urls.

**Comment by nathaneastwood** [comment]
@AnnCorp requested that we look at this in this sprint if possibly?

**Comment by dougmet** [comment]
Right-oh.
