### ISSUE TITLE
Format metadata numerator and denominator

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#97]
How can we style these to read more easily?

**Comment by shaneporter** [comment]
Can you give an example @dougmet?

**Comment by dougmet** [comment]
An example of where the data is filled in is: https://datasciencecampus.github.io/sdg-indicators/8-2-1/ but I think we need more guidance before making a change. Is there an "on hold" label?

**Comment by dougmet** [comment]
Under `Method of Computation`

**Comment by shaneporter** [comment]
Thanks.
