### ISSUE TITLE
The England and Wales problem

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#98]
I'm creating this ticket as a central point of conversation.

Data that is "United Kingdom" has region removed and this is interpreted as the "All" field. For many of our indicators we only have data for England and Wales before 2008. This causes a few headaches for the disaggregation.

Questions:

1. How common is it that data is for England and Wales before 2008?
2. Are there any other high level regions that could pop up.
3. Can we deal with this using a notice (e.g. `data before 2008 is for England and Wales only`) somewhere in the metadata?

**Comment by AlexLewis1** [comment]
At the moment it is a bit to early for us to tell for how many indicators the data will just be for England and Wales before 2008. I can imagine there will be quite a few cases where the data will be just for England and Wales like in 3.2.2 where there is only disaggregation of the data available for England and Wales which we can put in the metadata but the average user may just take the graph at face value and get confused by what is data for the UK and what is data only for England and Wales without reading the metadata.

I don't see any other high level regions that will come up and cause this issue. 

We will be writing what the data is measuring and any possible comments and limitations surrounding the data.

**Comment by MaxEngledew** [comment]
It is likely that, especially early in this process, a lot of data (not just pre 08) will be have England and Wales as the headline geographical coverage. This should be reflected in the "geographic coverage" section of the metadata. My, potentially incorrect assumption, is that "all" simply means the headline data for the indicator, so if we're consistently clear about what our headline "all" data's geographical coverage is then this shouldn't be a problem.

**Comment by dougmet** [comment]
OK, this is interesting. So we need a good language to talk about headlines and default views. As discussed in #90 it could be that we switch on certain disaggregations by default. In the case of 3.2.2 I wonder if it would be better to include a note somewhere that before 2008 it is England and Wales only, and then within the data reassign England and Wales to "All" (blank).

**Comment by MaxEngledew** [comment]
We don't use England and Wales pre 2008 and UK post 2008 - they are separate figures with minute differences. England and Wales does continue beyond 2008, it's just hard to see as it is very closely aligned with the UK figures. For example in 2009 England and wales = 5.19 and UK = 5.18 if we were to use that note would we not loose post 08 England and Wales figures?

**Comment by dougmet** [comment]
Yes we would lose it. OK, I think this is big enough to warrant bigger discussion this week

**Comment by dougmet** [comment]
I'm going to take this out of the sprint because it is downstream of #129 or at least it's a bit too vague for an action.

**Comment by nathaneastwood** [comment]
I think with the new filtering system in b9f00f4, this is sort of tackled as users can now filter out "UK" and/or "England and Wales". Or is there a bigger issue afoot here?

**Comment by AnnCorp** [comment]
@MaxEngledew is this something we still need to consider as part of filtering and disaggregations

**Comment by MaxEngledew** [comment]
I don't think so as the metadata seems to carrying through to the geographical coverage footnote on the graph so the "all" figure is clear
